import type Database from "better-sqlite3";

export type AgentKind = "brand" | "content" | "growth" | "client" | "revenue" | "opportunity" | "operations" | "creative" | "coding" | "trading";
export type AgentStatus = "queued" | "planning" | "waiting_approval" | "running" | "completed" | "failed" | "cancelled";
export interface AgentDefinition { id: number; agentKey: string; templateKey: AgentKind; name: string; description: string; mission: string; enabled: boolean; projectKeys: string[]; allowedToolKeys: string[]; deniedToolKeys: string[]; allowRag: boolean; ragProjectScoped: true; allowApprovedMemory: boolean; memoryProjectScoped: true; allowScheduler: boolean; responseMode: "concise" | "detailed"; modelMode: "default" | "fast"; createdAt: string; updatedAt: string; }
export type AgentInput = Omit<AgentDefinition,"id" | "createdAt" | "updatedAt" | "ragProjectScoped" | "memoryProjectScoped">;
export interface AgentStep { title: string; type: "research" | "analysis" | "tool_request" | "report"; toolKey?: string; requiresApproval: boolean; }
export interface AgentRun { id: number; agentId: number; projectKey: string; objective: string; status: AgentStatus; plan: { objective: string; steps: AgentStep[] }; contextUsed: Array<{ type: string; id: number | string; title: string; projectKey: string | null }>; toolsRequested: string[]; approvalsCreated: number[]; result: string | null; startedAt: string; completedAt: string | null; }
export interface ToolInfo { toolKey: string; enabled: boolean; riskLevel: "read_only" | "low_risk_write" | "medium_risk" | "high_risk"; requiresApproval: boolean; }
export class AgentError extends Error { constructor(message: string, readonly code: "validation" | "not_found" | "blocked" = "validation") { super(message); } }
const templates: Array<[AgentKind,string,string,string[]]> = [
 ["brand","Brand Agent","Maintain brand consistency, positioning, messaging, identity, and audience fit.",[]],
 ["content","Content Agent","Plan, create, repurpose, and organize content within approved brand and project scope.",["notes.create_project_note"]],
 ["growth","Growth / Sales Agent","Find growth opportunities and improve outreach strategy, lead systems, funnels, and sales processes.",[]],
 ["client","Client Agent","Track client context, deliverables, follow-ups, and service quality.",[]],
 ["revenue","Revenue Agent","Identify legitimate revenue, pricing, monetization, and operational improvements.",[]],
 ["opportunity","Opportunity Agent","Research contracts, jobs, grants, partnerships, markets, and business opportunities.",[]],
 ["operations","Operations Agent","Improve workflows, documentation, processes, task systems, and efficiency.",["scheduler.schedule.create"]],
 ["creative","Creative Agent","Support music, writing, video, design, storytelling, and creative development.",[]],
 ["coding","Coding Agent","Inspect code, propose changes through Safe Coding Workspace, and request approval for writes and commands.",["coding.status","coding.workspaces.list","coding.workspace.inspect","coding.file.read","coding.search","coding.git.status","coding.git.diff","coding.git.diff_file","coding.change.preview","coding.command.preview","coding.change.apply","coding.command.run"]],
 ["trading","Trading Agent","Research markets, strategies, backtests, paper positions, journals, performance, risk, watchlists, and setups. Never place live trades or move money.",[]],
];
export const AGENT_TEMPLATES = templates.map(([templateKey,name,mission,suggestedToolKeys]) => ({templateKey,name,mission,description:mission,suggestedToolKeys}));
export function isAgentDocumentAllowed(projectKey:string,documentProjectKey:string|null):boolean { return documentProjectKey===projectKey; }
export function isAgentMemoryAllowed(projectKey:string,memoryProjectKey:string|null):boolean { return memoryProjectKey===projectKey || memoryProjectKey===null; }
const forbidden = /^(trade\.|purchase\.|credentials\.|files\.delete$|email\.send$|deploy\.|financial\.|gambling\.|account\.delete|password\.)/;
const dangerousInteraction = /^(computer\.|browser\.(click|input|select|check|uncheck|form\.submit|download))/;
const projectAware = new Set(["notes.create_project_note","memory.create_proposal"]);
const safeGeneric = new Set(["system.status.snapshot","memory.status","research.status","voice.status","coding.status","scheduler.status","browser.status"]);
const browserRead = new Set(["browser.page.inspect","browser.page.text","browser.page.links","browser.page.forms","browser.page.elements","browser.page.screenshot","browser.navigation.preview","browser.form.preview","browser.navigate"]);
const codingScoped = new Set(["coding.workspace.inspect","coding.file.read","coding.search","coding.git.status","coding.git.diff","coding.git.diff_file","coding.change.preview","coding.command.preview","coding.change.apply","coding.command.run"]);
const supportedTool = (key:string) => safeGeneric.has(key) || projectAware.has(key) || browserRead.has(key) || codingScoped.has(key) || ["scheduler.schedule.preview","scheduler.schedule.create"].includes(key);
function required(value: unknown, label: string, max=4000): string { if (typeof value!=="string" || !value.trim() || value.length>max) throw new AgentError(`${label} is required and must be at most ${max} characters.`); return value.trim(); }
function keys(value: unknown, label: string): string[] { if (!Array.isArray(value) || value.some(x=>typeof x!=="string" || !/^[a-z0-9][a-z0-9._-]{0,100}$/.test(x))) throw new AgentError(`${label} must be an array of keys.`); return [...new Set(value)]; }
function bool(value: unknown): boolean { return value===true; }
const parse = (value: unknown): any => JSON.parse(String(value));
function definition(row: any): AgentDefinition { return {id:row.id,agentKey:row.agent_key,templateKey:row.template_key,name:row.name,description:row.description,mission:row.mission,enabled:!!row.enabled,projectKeys:parse(row.project_keys),allowedToolKeys:parse(row.allowed_tool_keys),deniedToolKeys:parse(row.denied_tool_keys),allowRag:!!row.allow_rag,ragProjectScoped:true,allowApprovedMemory:!!row.allow_approved_memory,memoryProjectScoped:true,allowScheduler:!!row.allow_scheduler,responseMode:row.response_mode,modelMode:row.model_mode,createdAt:row.created_at,updatedAt:row.updated_at}; }
function runRow(row:any): AgentRun { return {id:row.id,agentId:row.agent_id,projectKey:row.project_key,objective:row.objective,status:row.status,plan:parse(row.plan),contextUsed:parse(row.context_used),toolsRequested:parse(row.tools_requested),approvalsCreated:parse(row.approvals_created),result:row.result,startedAt:row.started_at,completedAt:row.completed_at}; }
export class AgentStore {
 constructor(readonly db: Database.Database, readonly lookupTool:(key:string)=>ToolInfo|null, readonly projectExists:(key:string)=>boolean, readonly codingRoot?:string) { this.initialize(); }
 private assertEnabled():void { if(process.env.AGENTS_ENABLED==="false") throw new AgentError("Agent subsystem is disabled.","blocked"); }
 initialize():void { this.db.exec(`CREATE TABLE IF NOT EXISTS agent_definitions (id INTEGER PRIMARY KEY AUTOINCREMENT,agent_key TEXT NOT NULL UNIQUE,template_key TEXT NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL,mission TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0,project_keys TEXT NOT NULL,allowed_tool_keys TEXT NOT NULL,denied_tool_keys TEXT NOT NULL,allow_rag INTEGER NOT NULL,allow_approved_memory INTEGER NOT NULL,allow_scheduler INTEGER NOT NULL,response_mode TEXT NOT NULL,model_mode TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,deleted_at TEXT); CREATE TABLE IF NOT EXISTS agent_runs (id INTEGER PRIMARY KEY AUTOINCREMENT,agent_id INTEGER NOT NULL,project_key TEXT NOT NULL,objective TEXT NOT NULL,status TEXT NOT NULL,plan TEXT NOT NULL,context_used TEXT NOT NULL DEFAULT '[]',tools_requested TEXT NOT NULL DEFAULT '[]',approvals_created TEXT NOT NULL DEFAULT '[]',result TEXT,started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at TEXT,FOREIGN KEY(agent_id) REFERENCES agent_definitions(id)); CREATE INDEX IF NOT EXISTS idx_agent_runs_agent ON agent_runs(agent_id,started_at); CREATE INDEX IF NOT EXISTS idx_agent_runs_status ON agent_runs(status);`); const columns=this.db.pragma("table_info(agent_definitions)") as Array<{name:string}>; if(!columns.some(c=>c.name==="deleted_at")) this.db.exec("ALTER TABLE agent_definitions ADD COLUMN deleted_at TEXT"); }
 validate(value:unknown):AgentInput { this.assertEnabled(); const x=value as Record<string,unknown>; if (!x || typeof x!=="object" || Array.isArray(x)) throw new AgentError("Agent definition is required."); const templateKey=required(x.templateKey,"templateKey",40) as AgentKind; if (!AGENT_TEMPLATES.some(t=>t.templateKey===templateKey)) throw new AgentError("Unknown agent template."); const projectKeys=keys(x.projectKeys,"projectKeys"); if (!projectKeys.length || projectKeys.some(k=>!this.projectExists(k))) throw new AgentError("Select existing projects explicitly."); const allowedToolKeys=keys(x.allowedToolKeys,"allowedToolKeys"); const deniedToolKeys=keys(x.deniedToolKeys,"deniedToolKeys"); for(const key of allowedToolKeys) { const tool=this.lookupTool(key); if (!tool || !tool.enabled || tool.riskLevel==="high_risk" || forbidden.test(key)) throw new AgentError(`Tool ${key} is unavailable or globally blocked.`,"blocked"); if (!supportedTool(key)) throw new AgentError(`Tool ${key} has no agent scope adapter.`,"blocked"); if (dangerousInteraction.test(key)) throw new AgentError(`Agent access to ${key} is blocked in this phase.`,"blocked"); if(key.startsWith("scheduler.") && key!=="scheduler.status" && !bool(x.allowScheduler)) throw new AgentError("Scheduler permission is required.","blocked"); if(key.startsWith("coding.") && templateKey!=="coding") throw new AgentError("Coding tools require a Coding Agent.","blocked"); }
 if(templateKey==="trading" && allowedToolKeys.some(k=>this.lookupTool(k)?.riskLevel!=="read_only" || dangerousInteraction.test(k) || k.startsWith("scheduler.")&&k!=="scheduler.status" || k.startsWith("coding."))) throw new AgentError("Trading Agent is research only.","blocked");
 return {agentKey:required(x.agentKey,"agentKey",80).toLowerCase(),templateKey,name:required(x.name,"name",120),description:typeof x.description==="string"?x.description.slice(0,500):"",mission:required(x.mission,"mission",4000),enabled:false,projectKeys,allowedToolKeys,deniedToolKeys,allowRag:bool(x.allowRag),allowApprovedMemory:bool(x.allowApprovedMemory),allowScheduler:bool(x.allowScheduler),responseMode:x.responseMode==="detailed"?"detailed":"concise",modelMode:x.modelMode==="fast"?"fast":"default"}; }
 preview(value:unknown) { const agent=this.validate(value); return {...agent,ragProjectScoped:true,memoryProjectScoped:true,approvalBehavior:"Writes and actions require a Tool Runner request and human approval.",dangerousCapabilities:agent.allowedToolKeys.filter(k=>this.lookupTool(k)?.riskLevel!=="read_only")}; }
 create(value:unknown):AgentDefinition { const a=this.validate(value); const result=this.db.prepare("INSERT INTO agent_definitions(agent_key,template_key,name,description,mission,enabled,project_keys,allowed_tool_keys,denied_tool_keys,allow_rag,allow_approved_memory,allow_scheduler,response_mode,model_mode) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(a.agentKey,a.templateKey,a.name,a.description,a.mission,0,JSON.stringify(a.projectKeys),JSON.stringify(a.allowedToolKeys),JSON.stringify(a.deniedToolKeys),Number(a.allowRag),Number(a.allowApprovedMemory),Number(a.allowScheduler),a.responseMode,a.modelMode); return this.get(Number(result.lastInsertRowid)); }
 update(id:number,value:unknown):AgentDefinition { this.get(id); const a=this.validate(value); const prior=this.get(id); this.db.prepare("UPDATE agent_definitions SET agent_key=?,template_key=?,name=?,description=?,mission=?,enabled=?,project_keys=?,allowed_tool_keys=?,denied_tool_keys=?,allow_rag=?,allow_approved_memory=?,allow_scheduler=?,response_mode=?,model_mode=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(a.agentKey,a.templateKey,a.name,a.description,a.mission,Number(prior.enabled),JSON.stringify(a.projectKeys),JSON.stringify(a.allowedToolKeys),JSON.stringify(a.deniedToolKeys),Number(a.allowRag),Number(a.allowApprovedMemory),Number(a.allowScheduler),a.responseMode,a.modelMode,id); return this.get(id); }
 setEnabled(id:number,enabled:boolean):AgentDefinition { this.assertEnabled(); this.get(id); this.db.prepare("UPDATE agent_definitions SET enabled=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(Number(enabled),id); return this.get(id); }
 delete(id:number):void { this.get(id); this.db.prepare("UPDATE agent_definitions SET enabled=0,deleted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(id); }
 get(id:number):AgentDefinition { const row=this.db.prepare("SELECT * FROM agent_definitions WHERE id=? AND deleted_at IS NULL").get(id); if(!row) throw new AgentError("Agent not found.","not_found"); return definition(row); }
 list():AgentDefinition[] { return (this.db.prepare("SELECT * FROM agent_definitions WHERE deleted_at IS NULL ORDER BY id DESC").all() as any[]).map(definition); }
 status() { const count=(sql:string)=>Number((this.db.prepare(sql).get() as any).n); return {enabled:process.env.AGENTS_ENABLED!=="false",enabledAgents:count("SELECT COUNT(*) n FROM agent_definitions WHERE enabled=1 AND deleted_at IS NULL"),activeRuns:count("SELECT COUNT(*) n FROM agent_runs WHERE status IN ('queued','planning','running')"),waitingApprovals:count("SELECT COUNT(*) n FROM agent_runs WHERE status='waiting_approval'")}; }
 assertTool(agent:AgentDefinition,projectKey:string,key:string,args:Record<string,unknown>):ToolInfo { if(!agent.enabled) throw new AgentError("Agent is disabled.","blocked"); if(!agent.projectKeys.includes(projectKey)) throw new AgentError("Project is outside agent scope.","blocked"); if(forbidden.test(key)||dangerousInteraction.test(key)||agent.deniedToolKeys.includes(key)||!agent.allowedToolKeys.includes(key)) throw new AgentError(`Tool ${key} is outside agent permissions.`,"blocked"); const tool=this.lookupTool(key); if(!tool?.enabled || tool.riskLevel==="high_risk") throw new AgentError("Tool is globally blocked.","blocked"); if(key.startsWith("scheduler.") && key!=="scheduler.status" && !agent.allowScheduler) throw new AgentError("Scheduler permission is disabled.","blocked"); if(key==="scheduler.schedule.create" && (args.projectKey!==projectKey || typeof args.actionToolKey!=="string" || !agent.allowedToolKeys.includes(args.actionToolKey) || !safeGeneric.has(args.actionToolKey) || args.enabled!==false)) throw new AgentError("Agent schedule proposals must be disabled and target an allowed read-only status tool in the same project.","blocked"); if(key.startsWith("scheduler.") && !["scheduler.status","scheduler.schedule.preview","scheduler.schedule.create"].includes(key)) throw new AgentError("Agent scheduler administration is unavailable.","blocked"); if(key.startsWith("coding.") && agent.templateKey!=="coding") throw new AgentError("Coding tools require Coding Agent.","blocked"); if(key.startsWith("coding.") && !["coding.status","coding.workspaces.list"].includes(key) && (projectKey!=="freeos" || !this.codingRoot || args.workspaceRoot!==this.codingRoot)) throw new AgentError("Coding tool must use the bound FREEOS workspace.","blocked"); if(!supportedTool(key)) throw new AgentError("Tool lacks a verified project scope adapter.","blocked"); if(projectAware.has(key) && args.projectKey!==projectKey) throw new AgentError("Tool project must match the run project.","blocked"); if(agent.templateKey==="trading" && tool.riskLevel!=="read_only") throw new AgentError("Trading Agent is read only.","blocked"); return tool; }
 previewRun(id:number,projectKey:string,objective:string,requests:Array<{toolKey:string;args:Record<string,unknown>}>=[]) { this.assertEnabled(); const agent=this.get(id); required(objective,"objective",4000); if(!agent.enabled || !agent.projectKeys.includes(projectKey)) throw new AgentError("Agent is disabled or project is outside scope.","blocked"); if(requests.length>5) throw new AgentError("At most five structured tool requests per run."); const steps:AgentStep[]=[{title:"Read approved project context",type:"research",requiresApproval:false},...requests.map(r=>({title:`Request ${r.toolKey}`,type:"tool_request" as const,toolKey:r.toolKey,requiresApproval:this.assertTool(agent,projectKey,r.toolKey,r.args).riskLevel!=="read_only"})),{title:"Report findings",type:"report",requiresApproval:false}]; return {agentId:id,mission:agent.mission,objective,projectKey,availableTools:agent.allowedToolKeys.filter(k=>!agent.deniedToolKeys.includes(k)),approvalBehavior:"All action tools create a pending human approval request.",plan:{objective,steps}}; }
 start(id:number,projectKey:string,objective:string,requests:Array<{toolKey:string;args:Record<string,unknown>}>=[]):AgentRun { const preview=this.previewRun(id,projectKey,objective,requests); const result=this.db.prepare("INSERT INTO agent_runs(agent_id,project_key,objective,status,plan,tools_requested) VALUES (?,?,?,?,?,?)").run(id,projectKey,objective,"planning",JSON.stringify(preview.plan),JSON.stringify(requests.map(r=>r.toolKey))); return this.getRun(Number(result.lastInsertRowid)); }
 finish(id:number,status:AgentStatus,contextUsed:AgentRun["contextUsed"],approvalsCreated:number[],result:string|null):AgentRun { this.getRun(id); this.db.prepare("UPDATE agent_runs SET status=?,context_used=?,approvals_created=?,result=?,completed_at=CASE WHEN ? IN ('completed','failed','cancelled') THEN CURRENT_TIMESTAMP ELSE NULL END WHERE id=?").run(status,JSON.stringify(contextUsed),JSON.stringify(approvalsCreated),result,status,id); return this.getRun(id); }
 private syncRun(row:any):AgentRun { const run=runRow(row); if(run.status!=="waiting_approval" || !run.approvalsCreated.length) return run; const marks=run.approvalsCreated.map(id=>(this.db.prepare("SELECT status FROM tool_requests WHERE id=?").get(id) as {status:string}|undefined)?.status??"missing"); if(marks.some(status=>["pending","approved"].includes(status))) return run; const status=marks.every(x=>x==="completed")?"completed":marks.some(x=>x==="rejected")?"cancelled":"failed"; this.db.prepare("UPDATE agent_runs SET status=?,completed_at=CURRENT_TIMESTAMP WHERE id=? AND status='waiting_approval'").run(status,run.id); return {...run,status,completedAt:new Date().toISOString()}; }
 getRun(id:number):AgentRun { const row=this.db.prepare("SELECT * FROM agent_runs WHERE id=?").get(id); if(!row) throw new AgentError("Run not found.","not_found"); return this.syncRun(row); }
 listRuns(limit=100):AgentRun[] { return (this.db.prepare("SELECT * FROM agent_runs ORDER BY id DESC LIMIT ?").all(Math.min(Math.max(limit,1),500)) as any[]).map(row=>this.syncRun(row)); }
}
