import type { AutomationRule, CreateAutomationRuleInput } from "./automation.types";
import type { JsonObject } from "./tool.types";
import { ToolRunnerError } from "./tool.types";
import { getToolRegistry, type ToolRegistry } from "./toolRegistry";
import { ToolRequests } from "./toolRequests";
import { ToolExecutor } from "./toolExecutor";

type Row = Record<string, unknown>;
function parse(value: unknown): JsonObject { try { const result: unknown = JSON.parse(String(value)); return result && typeof result === "object" && !Array.isArray(result) ? result as JsonObject : {}; } catch { return {}; } }
function fromRow(row: Row): AutomationRule { return { id: Number(row.id), ruleKey: String(row.rule_key), name: String(row.name), description: String(row.description), enabled: Boolean(row.enabled), triggerType: String(row.trigger_type) as AutomationRule["triggerType"], triggerConfig: parse(row.trigger_config), actionToolKey: String(row.action_tool_key), actionArgs: parse(row.action_args), requiresApproval: Boolean(row.requires_approval), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }

export class AutomationService {
  readonly requests: ToolRequests; readonly executor: ToolExecutor;
  constructor(readonly registry: ToolRegistry = getToolRegistry()) { this.requests = new ToolRequests(registry); this.executor = new ToolExecutor(registry); }
  createAutomationRule(input: CreateAutomationRuleInput): AutomationRule {
    if (!input.ruleKey?.trim() || !/^[a-z0-9][a-z0-9._-]*$/i.test(input.ruleKey)) throw new ToolRunnerError("ruleKey must use letters, numbers, dots, dashes, or underscores.", "validation");
    if (!input.name?.trim()) throw new ToolRunnerError("name is required.", "validation");
    if (!(["manual", "interval_preview"] as string[]).includes(input.triggerType)) throw new ToolRunnerError("triggerType must be manual or interval_preview.", "validation");
    const tool = this.registry.requireTool(input.actionToolKey);
    if (tool.riskLevel === "high_risk" || !tool.enabled) throw new ToolRunnerError("Automation actions cannot target blocked or disabled tools.", "blocked");
    try { this.registry.database.prepare(`INSERT INTO automation_rules (rule_key,name,description,enabled,trigger_type,trigger_config,action_tool_key,action_args,requires_approval) VALUES (?,?,?,?,?,?,?,?,?)`).run(input.ruleKey.trim(), input.name.trim(), input.description?.trim() ?? "", Number(input.enabled ?? false), input.triggerType, JSON.stringify(input.triggerConfig ?? {}), tool.toolKey, JSON.stringify(input.actionArgs ?? {}), Number(tool.riskLevel !== "read_only" || tool.requiresApproval)); }
    catch (error) { throw new ToolRunnerError(error instanceof Error && error.message.includes("UNIQUE") ? "An automation rule with that ruleKey already exists." : "Could not create automation rule.", error instanceof Error && error.message.includes("UNIQUE") ? "conflict" : "database"); }
    this.event(input.ruleKey, "created", "Automation rule created.", { actionToolKey: tool.toolKey }); this.registry.logEvent("automation.rule.created", `Automation rule ${input.ruleKey} created.`, { ruleKey: input.ruleKey }); return this.get(input.ruleKey);
  }
  get(ruleKey: string): AutomationRule { const row = this.registry.database.prepare("SELECT * FROM automation_rules WHERE rule_key=?").get(ruleKey) as Row | undefined; if (!row) throw new ToolRunnerError("Automation rule not found.", "not_found"); return fromRow(row); }
  listAutomationRules(): AutomationRule[] { return (this.registry.database.prepare("SELECT * FROM automation_rules ORDER BY id DESC").all() as Row[]).map(fromRow); }
  setEnabled(ruleKey: string, enabled: boolean): AutomationRule { this.get(ruleKey); this.registry.database.prepare("UPDATE automation_rules SET enabled=?,updated_at=CURRENT_TIMESTAMP WHERE rule_key=?").run(Number(enabled), ruleKey); this.event(ruleKey, enabled ? "enabled" : "disabled", `Automation rule ${enabled ? "enabled" : "disabled"}.`); this.registry.logEvent(`automation.rule.${enabled ? "enabled" : "disabled"}`, `Automation rule ${ruleKey} ${enabled ? "enabled" : "disabled"}.`, { ruleKey }); return this.get(ruleKey); }
  enableAutomationRule(ruleKey: string) { return this.setEnabled(ruleKey, true); }
  disableAutomationRule(ruleKey: string) { return this.setEnabled(ruleKey, false); }
  async runAutomationCheckOnce(ruleKey: string): Promise<{ rule: AutomationRule; request?: unknown; run?: unknown; message: string }> {
    const rule = this.get(ruleKey); if (!rule.enabled) throw new ToolRunnerError("Enable the automation rule before checking it.", "blocked");
    const tool = this.registry.requireTool(rule.actionToolKey);
    if (rule.requiresApproval || tool.riskLevel !== "read_only") {
      const request = this.requests.createToolRequest({ toolKey: tool.toolKey, title: `Automation: ${rule.name}`, description: `Preview generated by ${rule.ruleKey}. No action has run.`, args: rule.actionArgs, requestedBy: `automation:${rule.ruleKey}` });
      this.event(ruleKey, "approval_pending", `Created tool request #${request.id}; no action executed.`, { requestId: request.id }); this.registry.logEvent("automation.check.approval_pending", `Automation ${ruleKey} created request #${request.id}.`, { ruleKey, requestId: request.id }); return { rule, request, message: "Approval request created. No action executed." };
    }
    const run = await this.executor.runReadOnlyTool(tool.toolKey, rule.actionArgs); this.event(ruleKey, "completed", `Read-only check completed as run #${run.id}.`, { runId: run.id }); this.registry.logEvent("automation.check.completed", `Automation ${ruleKey} completed read-only run #${run.id}.`, { ruleKey, runId: run.id }); return { rule, run, message: "Read-only automation check completed." };
  }
  private event(ruleKey: string, status: string, message: string, metadata: unknown = {}): void { this.registry.database.prepare("INSERT INTO automation_events (rule_key,status,message,metadata) VALUES (?,?,?,?)").run(ruleKey, status, message, JSON.stringify(metadata)); }
}

export const createAutomationRule = (input: CreateAutomationRuleInput) => new AutomationService().createAutomationRule(input);
export const listAutomationRules = () => new AutomationService().listAutomationRules();
export const enableAutomationRule = (key: string) => new AutomationService().enableAutomationRule(key);
export const disableAutomationRule = (key: string) => new AutomationService().disableAutomationRule(key);
export const runAutomationCheckOnce = (key: string) => new AutomationService().runAutomationCheckOnce(key);
