import test from "node:test";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const require=createRequire(import.meta.url);
const {AgentStore,isAgentDocumentAllowed,isAgentMemoryAllowed}=require("../../packages/agent-core/dist/index.js");
const {ToolRegistry,ToolRequests,ToolExecutor}=require("../../packages/tool-runner/dist/index.js");
const {BrowserOperator}=require("../../packages/browser-core/dist/index.js");
const {isComputerControlAllowed}=require("../../packages/computer-core/dist/index.js");

function fixture(){const root=mkdtempSync(join(tmpdir(),"freeos-agents-"));const registry=new ToolRegistry({rootDir:root,databasePath:join(root,"agents.sqlite")});registry.registerDefaultTools();const projectKeys=new Set(["dfb-solutions","reemteam","freeos","signalflow"]);const store=new AgentStore(registry.database,key=>registry.getToolByKey(key),key=>projectKeys.has(key),root);const cleanup=()=>{registry.close();rmSync(root,{recursive:true,force:true});};return {root,registry,store,cleanup};}
function input(overrides={}){return {agentKey:"test-agent",templateKey:"content",name:"Test Agent",description:"Test",mission:"Help the selected project.",enabled:true,projectKeys:["dfb-solutions"],allowedToolKeys:["voice.status"],deniedToolKeys:[],allowRag:true,allowApprovedMemory:true,allowScheduler:false,responseMode:"concise",modelMode:"default",...overrides};}

test("project scope and unrelated context are denied",()=>{const f=fixture();try{const agent=f.store.create(input());assert.throws(()=>f.store.previewRun(agent.id,"reemteam","Plan content"),/outside scope/);assert.equal(isAgentDocumentAllowed("dfb-solutions","reemteam"),false);assert.equal(isAgentDocumentAllowed("dfb-solutions",null),false);assert.equal(isAgentDocumentAllowed("dfb-solutions","dfb-solutions"),true);assert.equal(isAgentMemoryAllowed("dfb-solutions","reemteam"),false);assert.equal(isAgentMemoryAllowed("dfb-solutions",null),true);}finally{f.cleanup();}});
test("disallowed and high-risk tools cannot be granted or requested",()=>{const f=fixture();try{const a=f.store.create(input());assert.throws(()=>f.store.previewRun(a.id,"dfb-solutions","Try a tool",[{toolKey:"notes.create_project_note",args:{projectKey:"dfb-solutions"}}]),/outside agent permissions/);assert.throws(()=>f.store.preview(input({allowedToolKeys:["trade.place_order"]})),/blocked/);assert.throws(()=>f.store.preview(input({allowedToolKeys:["credentials.read"]})),/blocked/);}finally{f.cleanup();}});
test("allowed read-only agent tool executes and is audited",async()=>{const f=fixture();try{const a=f.store.create(input());const run=f.store.start(a.id,"dfb-solutions","Check status",[{toolKey:"voice.status",args:{}}]);const toolRun=await new ToolExecutor(f.registry).runReadOnlyTool("voice.status");assert.equal(toolRun.status,"completed");assert.equal(toolRun.output.voiceEnabled !== undefined,true);const saved=f.store.finish(run.id,"completed",[{type:"project_note",id:1,title:"Test",projectKey:"dfb-solutions"}],[],"Status inspected.");assert.equal(f.store.getRun(saved.id).contextUsed[0].projectKey,"dfb-solutions");assert.equal(f.store.listRuns()[0].result,"Status inspected.");}finally{f.cleanup();}});
test("medium-risk request stays pending for human approval",()=>{const f=fixture();try{const a=f.store.create(input({allowedToolKeys:["notes.create_project_note"]}));const args={projectKey:"dfb-solutions",title:"Draft",content:"Safe text"};f.store.previewRun(a.id,"dfb-solutions","Write note",[{toolKey:"notes.create_project_note",args}]);const request=new ToolRequests(f.registry).createToolRequest({toolKey:"notes.create_project_note",title:"Agent note",args,requestedBy:`agent:${a.id}:run:1`});assert.equal(request.status,"pending");assert.equal(f.registry.database.prepare("SELECT COUNT(*) n FROM tool_runs WHERE request_id=?").get(request.id).n,0);assert.throws(()=>f.store.previewRun(a.id,"dfb-solutions","Wrong project",[{toolKey:"notes.create_project_note",args:{...args,projectKey:"reemteam"}}]),/project must match/);}finally{f.cleanup();}});
test("disabled agent and Trading Agent cannot execute",()=>{const f=fixture();try{const a=f.store.create(input({enabled:false}));assert.throws(()=>f.store.previewRun(a.id,"dfb-solutions","Do work"),/disabled/);assert.throws(()=>f.store.preview(input({templateKey:"trading",projectKeys:["signalflow"],allowedToolKeys:["trade.place_order"]})),/blocked/);assert.throws(()=>f.store.preview(input({templateKey:"trading",projectKeys:["signalflow"],allowedToolKeys:["browser.navigate"]})),/research only/);}finally{f.cleanup();}});
test("Coding Agent is bound to FREEOS workspace and still needs approval",()=>{const f=fixture();try{const a=f.store.create(input({templateKey:"coding",projectKeys:["freeos"],allowedToolKeys:["coding.file.read","coding.change.apply"]}));assert.throws(()=>f.store.previewRun(a.id,"freeos","Inspect",[{toolKey:"coding.file.read",args:{workspaceRoot:"C:\\unrelated",path:"README.md"}}]),/bound FREEOS workspace/);assert.throws(()=>f.store.previewRun(a.id,"dfb-solutions","Inspect"),/outside scope/);f.store.previewRun(a.id,"freeos","Apply preview",[{toolKey:"coding.change.apply",args:{workspaceRoot:f.root,previewId:"test-preview"}}]);const request=new ToolRequests(f.registry).createToolRequest({toolKey:"coding.change.apply",title:"Apply preview",args:{workspaceRoot:f.root,previewId:"test-preview"}});assert.equal(request.status,"pending");assert.equal(f.registry.database.prepare("SELECT COUNT(*) n FROM tool_runs WHERE request_id=?").get(request.id).n,0);}finally{f.cleanup();}});
test("Browser origin grant and agent permission are independent",()=>{const f=fixture();try{const browser=new BrowserOperator(f.root);assert.equal(browser.permission("https://example.invalid","navigate"),false);const a=f.store.create(input({allowedToolKeys:["browser.navigate"]}));f.store.previewRun(a.id,"dfb-solutions","Inspect public site",[{toolKey:"browser.navigate",args:{url:"https://example.invalid/"}}]);assert.throws(()=>f.store.preview(input({allowedToolKeys:["browser.form.submit"]})),/scope adapter|blocked/);assert.equal(browser.permission("https://example.invalid","navigate"),false);}finally{f.cleanup();}});
test("scheduler proposal is disabled and cannot silently create a schedule",()=>{const f=fixture();try{const a=f.store.create(input({allowScheduler:true,allowedToolKeys:["scheduler.status","scheduler.schedule.create"]}));const args={projectKey:"dfb-solutions",name:"Status",actionToolKey:"scheduler.status",actionArgs:{},scheduleConfig:{type:"once",at:"2030-01-01T00:00:00.000Z"},enabled:false};f.store.previewRun(a.id,"dfb-solutions","Propose schedule",[{toolKey:"scheduler.schedule.create",args}]);const request=new ToolRequests(f.registry).createToolRequest({toolKey:"scheduler.schedule.create",title:"Schedule proposal",args});assert.equal(request.status,"pending");assert.throws(()=>f.store.previewRun(a.id,"dfb-solutions","Auto schedule",[{toolKey:"scheduler.schedule.create",args:{...args,enabled:true}}]),/disabled/);assert.throws(()=>f.store.previewRun(a.id,"dfb-solutions","Wrong target",[{toolKey:"scheduler.schedule.create",args:{...args,actionToolKey:"trade.place_order"}}]),/disabled/);}finally{f.cleanup();}});
test("Computer control switch and agent policy cannot be bypassed",()=>{const f=fixture();try{const original=process.env.COMPUTER_CONTROL_ENABLED;process.env.COMPUTER_CONTROL_ENABLED="false";assert.equal(isComputerControlAllowed(),false);assert.throws(()=>f.store.preview(input({allowedToolKeys:["computer.mouse.click"]})),/scope adapter|blocked/);if(original===undefined)delete process.env.COMPUTER_CONTROL_ENABLED;else process.env.COMPUTER_CONTROL_ENABLED=original;}finally{f.cleanup();}});
test("run history survives soft deletion",()=>{const f=fixture();try{const a=f.store.create(input());const run=f.store.start(a.id,"dfb-solutions","Audit result");f.store.finish(run.id,"completed",[],[],"Saved");f.store.delete(a.id);assert.equal(f.store.list().length,0);assert.equal(f.store.getRun(run.id).result,"Saved");}finally{f.cleanup();}});
