import { chromium, type BrowserContext, type Page, type Locator } from "playwright-core";
import { existsSync, lstatSync, mkdirSync, readFileSync, writeFileSync, readdirSync, unlinkSync } from "node:fs";
import { resolve, join, relative, isAbsolute, sep, basename, dirname } from "node:path";
import { randomUUID } from "node:crypto";

export class BrowserError extends Error { constructor(message: string, readonly code: "blocked" | "validation" | "unavailable" | "not_found" = "blocked") { super(message); } }
export type Permission = "observe" | "navigate" | "interact" | "download";
export type SitePermission = { origin: string; permissions: Permission[]; enabled: boolean };
type Ref = { id: string; tabId: string; revision: number; kind: string; marker: string; strategy: "role" | "label" | "text" | "testid" | "css"; role: string; testId: string; selector: string; label: string; sensitive: boolean; financial: boolean; intent: string; formPreview?: { origin: string; action: string; method: string; fields: Array<{ name: string; type: string; value: string }>; submitButton: string; requiresApproval: boolean } };
type Tab = { id: string; page: Page; revision: number; refs: Map<string, Ref> };
type Session = { id: string; createdAt: string; status: "active" | "stopped"; currentUrl: string | null; tabIds: string[]; originsVisited: string[]; actions: Array<{ at: string; action: string; url: string; requestId?: number }>; screenshots: string[] };
const dangerous = /\b(buy|purchase|checkout|pay now|place order|trade|sell shares|transfer money|wire transfer|gamble|bet now|publish|post|send|message|email|apply for job|submit application|sign agreement|delete[\s_-]*account|delete[\s_-]*data|change[\s_-]*password)\b/i;
const financial = /\b(card|credit|debit|cvv|cvc|payment|bank|routing|iban|account number|ssn|social security)\b/i;
const sensitive = /\b(password|passcode|secret|token|api key|private key|ssn|social security|card|cvv|cvc|bank|routing)\b/i;
const readKeys = new Set(["browser.status", "browser.sessions.list", "browser.tabs.list", "browser.page.inspect", "browser.page.text", "browser.page.links", "browser.page.forms", "browser.page.elements", "browser.page.screenshot", "browser.navigation.preview", "browser.form.preview", "browser.session.start", "browser.session.stop"]);
const actionKeys = new Set(["browser.navigate", "browser.click", "browser.input", "browser.select", "browser.check", "browser.uncheck", "browser.form.submit", "browser.scroll", "browser.back", "browser.forward", "browser.reload", "browser.download"]);
export const isBrowserActionKey = (key: string) => actionKeys.has(key);
export type BrowserEngine = "chrome" | "edge";
export function resolveBrowserEngine(preferred = process.env.BROWSER_PREFERRED_ENGINE, exists: (path: string) => boolean = existsSync, env = process.env): { preferredEngine: BrowserEngine; activeEngine: BrowserEngine | null; executablePath: string | null } {
  const choice: BrowserEngine = preferred?.toLowerCase() === "edge" ? "edge" : "chrome";
  const dirs = [env.PROGRAMFILES, env["PROGRAMFILES(X86)"], env.LOCALAPPDATA].filter((value): value is string => Boolean(value));
  const candidates: Record<BrowserEngine, string[]> = {
    chrome: dirs.map(dir => join(dir, "Google", "Chrome", "Application", "chrome.exe")),
    edge: dirs.map(dir => join(dir, "Microsoft", "Edge", "Application", "msedge.exe")),
  };
  for (const engine of [choice, choice === "chrome" ? "edge" : "chrome"] as BrowserEngine[]) {
    const executablePath = candidates[engine].find(exists);
    if (executablePath) return { preferredEngine: choice, activeEngine: engine, executablePath };
  }
  return { preferredEngine: choice, activeEngine: null, executablePath: null };
}
const bool = (name: string, fallback: boolean) => (process.env[name] ?? String(fallback)).toLowerCase() === "true";
const bounded = (name: string, fallback: number, max: number) => { const n = Number(process.env[name]); return Number.isInteger(n) && n > 0 ? Math.min(n, max) : fallback; };
function within(parent: string, child: string): boolean { const rel = relative(parent, child); return rel === "" || (rel !== ".." && !rel.startsWith(`..${sep}`) && !isAbsolute(rel)); }
function safeDirectory(root: string, setting: string, fallback: string): string {
  const base = resolve(root, "data", "browser"); const path = resolve(root, setting || fallback);
  if (!within(base, path) || path === base) throw new BrowserError("Browser storage must stay inside data/browser.");
  let cursor = root; for (const part of relative(root, path).split(sep)) { cursor = join(cursor, part); if (existsSync(cursor) && lstatSync(cursor).isSymbolicLink()) throw new BrowserError("Browser storage cannot use links or reparse points."); }
  return path;
}
export function normalizeUrl(raw: unknown): { url: string; origin: string } {
  if (typeof raw !== "string" || !raw.trim() || raw.length > 4096) throw new BrowserError("A valid HTTP(S) URL is required.", "validation");
  let parsed: URL; try { parsed = new URL(raw.trim()); } catch { throw new BrowserError("Invalid URL.", "validation"); }
  if (!["http:", "https:"].includes(parsed.protocol)) throw new BrowserError("Only HTTP(S) URLs are allowed.");
  if (parsed.username || parsed.password) throw new BrowserError("Credential-bearing URLs are blocked.");
  if (!parsed.hostname) throw new BrowserError("URL host is required.", "validation");
  parsed.hash = ""; return { url: parsed.href, origin: parsed.origin };
}
function local(origin: string): boolean { const host = new URL(origin).hostname.toLowerCase(); return host === "localhost" || host === "127.0.0.1" || host === "[::1]"; }
function cleanLabel(value: unknown): string { return String(value ?? "").trim().slice(0, 160); }
function writeBrowserJson(root: string, path: string, value: unknown) { safeDirectory(root, "data/browser/profile", "data/browser/profile"); if (existsSync(path) && (lstatSync(path).isSymbolicLink() || !lstatSync(path).isFile())) throw new BrowserError("Browser metadata path is redirected."); mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, JSON.stringify(value, null, 2)); }
export function safeBrowserUrl(raw: unknown): string { try { const url = new URL(String(raw)); for (const key of url.searchParams.keys()) url.searchParams.set(key, "[redacted]"); return url.href; } catch { return "[invalid URL]"; } }

export class BrowserOperator {
  readonly root: string; readonly profileDir: string; readonly downloadDir: string; readonly screenshotDir: string; readonly permissionsFile: string; readonly sessionsFile: string;
  private context: BrowserContext | null = null; private session: Session | null = null; private history: Session[] = []; private tabs = new Map<string, Tab>();
  constructor(root = process.cwd()) { this.root = resolve(root); this.profileDir = safeDirectory(this.root, process.env.BROWSER_PROFILE_DIR ?? "", "data/browser/profile"); this.downloadDir = safeDirectory(this.root, process.env.BROWSER_DOWNLOAD_DIR ?? "", "data/browser/downloads"); this.screenshotDir = safeDirectory(this.root, "data/browser/screenshots", "data/browser/screenshots"); this.permissionsFile = resolve(this.root, "data/browser/permissions.json"); this.sessionsFile = resolve(this.root, "data/browser/sessions.json"); try { const rows = JSON.parse(readFileSync(this.sessionsFile, "utf8")); if (Array.isArray(rows)) this.history = rows.filter(s => s && typeof s.id === "string" && Array.isArray(s.actions)).map(s => ({ ...s, status: "stopped" })); } catch { /* no previous sessions */ } }
  private persist() { writeBrowserJson(this.root, this.sessionsFile, this.sessions()); }
  private enabled() { if (!bool("BROWSER_ENABLED", true)) throw new BrowserError("Browser Operator is disabled."); }
  private control() { this.enabled(); if (!bool("BROWSER_CONTROL_ENABLED", false)) throw new BrowserError("Browser control is disabled."); }
  permissions(): SitePermission[] { try { const rows = JSON.parse(readFileSync(this.permissionsFile, "utf8")); if (!Array.isArray(rows)) return []; return rows.filter((r): r is SitePermission => r && typeof r.origin === "string" && Array.isArray(r.permissions) && typeof r.enabled === "boolean").map(r => ({ origin: normalizeUrl(r.origin).origin, enabled: r.enabled, permissions: r.permissions.filter(p => ["observe", "navigate", "interact", "download"].includes(p)) })); } catch { return []; } }
  setPermissions(rows: SitePermission[]) { if (!Array.isArray(rows) || rows.length > 100) throw new BrowserError("Invalid site permissions.", "validation"); const clean = rows.map(r => { if (!r || !Array.isArray(r.permissions) || typeof r.enabled !== "boolean" || r.permissions.some(p => !["observe", "navigate", "interact", "download"].includes(p))) throw new BrowserError("Invalid site permission.", "validation"); return { origin: normalizeUrl(r.origin).origin, enabled: r.enabled, permissions: [...new Set(r.permissions)] }; }); writeBrowserJson(this.root, this.permissionsFile, clean); return clean; }
  permission(origin: string, kind: Permission): boolean { const row = this.permissions().find(r => r.origin === origin); if (row) return row.enabled && row.permissions.includes(kind); return local(origin) && (kind === "observe" || kind === "navigate"); }
  private requireOrigin(origin: string, kind: Permission) { if (!this.permission(origin, kind)) throw new BrowserError(`${kind} permission is not granted for ${origin}.`); }
  status() { const selected = resolveBrowserEngine(); const profilePath = relative(this.root, this.profileDir).replace(/\\/g, "/"); return { enabled: bool("BROWSER_ENABLED", true), controlEnabled: bool("BROWSER_CONTROL_ENABLED", false), screenshotEnabled: bool("BROWSER_SCREENSHOT_ENABLED", true), downloadsEnabled: bool("BROWSER_DOWNLOADS_ENABLED", false), headless: bool("BROWSER_HEADLESS", false), engine: selected.activeEngine, preferredEngine: selected.preferredEngine, activeEngine: selected.activeEngine, browserDetected: selected.activeEngine !== null, executableDetected: selected.executablePath !== null, profilePath, profilePersistent: true, profileIsolated: true, profileDir: profilePath, activeSession: this.session?.id ?? null, permissions: this.permissions(), maxTabs: bounded("BROWSER_MAX_TABS", 8, 32) }; }
  sessions() { return [...this.history, ...(this.session ? [this.session] : [])].map(s => ({ ...s, actions: [...s.actions] })); }
  async start() { this.enabled(); if (this.context) return this.session; const executablePath = resolveBrowserEngine().executablePath; if (!executablePath) throw new BrowserError("No local Edge or Chrome installation found.", "unavailable"); mkdirSync(this.profileDir, { recursive: true }); mkdirSync(this.downloadDir, { recursive: true }); this.context = await chromium.launchPersistentContext(this.profileDir, { executablePath, headless: bool("BROWSER_HEADLESS", false), acceptDownloads: false, downloadsPath: this.downloadDir }); await this.context.route("**/*", async route => { if (!route.request().isNavigationRequest()) { await route.continue(); return; } try { const target = normalizeUrl(route.request().url()); if (this.permission(target.origin, "navigate")) await route.continue(); else await route.abort(); } catch { await route.abort(); } }); this.session = { id: randomUUID(), createdAt: new Date().toISOString(), status: "active", currentUrl: null, tabIds: [], originsVisited: [], actions: [], screenshots: [] }; this.persist(); for (const page of this.context.pages()) this.attach(page); this.context.on("page", page => { if (this.tabs.size >= bounded("BROWSER_MAX_TABS", 8, 32)) { void page.close(); return; } this.attach(page); }); return this.session; }
  async stop() { if (!this.context) return { stopped: false }; const ctx = this.context; this.context = null; await ctx.close(); if (this.session) { this.session.status = "stopped"; this.history.push(this.session); } this.session = null; this.tabs.clear(); this.persist(); return { stopped: true }; }
  private attach(page: Page) { const tab: Tab = { id: randomUUID(), page, revision: 0, refs: new Map() }; this.tabs.set(tab.id, tab); this.session?.tabIds.push(tab.id); this.persist(); page.on("framenavigated", frame => { if (frame === page.mainFrame()) { tab.revision++; tab.refs.clear(); try { const target = normalizeUrl(page.url()); if (this.session) { this.session.currentUrl = safeBrowserUrl(target.url); if (!this.session.originsVisited.includes(target.origin)) this.session.originsVisited.push(target.origin); this.persist(); } if (!this.permission(target.origin, "observe")) void page.goto("about:blank").catch(() => {}); } catch { /* blank initial page */ } } }); page.on("close", () => this.tabs.delete(tab.id)); return tab; }
  tabsList() { return [...this.tabs.values()].map(t => ({ id: t.id, url: safeBrowserUrl(t.page.url()), title: t.page.isClosed() ? "" : "(inspect for title)", revision: t.revision })); }
  private tab(id?: unknown): Tab { const item = typeof id === "string" ? this.tabs.get(id) : [...this.tabs.values()][0]; if (!item || item.page.isClosed()) throw new BrowserError("Browser tab not found. Start a session first.", "not_found"); return item; }
  private observed(tab: Tab) { const { origin } = normalizeUrl(tab.page.url()); this.requireOrigin(origin, "observe"); return origin; }
  preview(url: unknown) { const target = normalizeUrl(url); return { url: safeBrowserUrl(target.url), origin: target.origin, permitted: this.permission(target.origin, "navigate"), requiresApproval: true, currentUrl: this.tabsList()[0]?.url ?? null }; }
  private record(action: string, page: Page, requestId?: number) { this.session?.actions.push({ at: new Date().toISOString(), action, url: safeBrowserUrl(page.url()), requestId }); this.persist(); }
  async navigate(url: unknown, tabId?: unknown, requestId?: number) { this.control(); const target = normalizeUrl(url); this.requireOrigin(target.origin, "navigate"); const tab = this.tab(tabId); const page = tab.page; const guard = async (route: import("playwright-core").Route) => { try { const t = normalizeUrl(route.request().url()); if (this.permission(t.origin, "navigate")) await route.continue(); else await route.abort(); } catch { await route.abort(); } }; await page.route("**/*", guard); try { await page.goto(target.url, { waitUntil: "domcontentloaded", timeout: bounded("BROWSER_NAVIGATION_TIMEOUT_MS", 45000, 120000) }); const final = normalizeUrl(page.url()); this.requireOrigin(final.origin, "navigate"); this.record("navigate", page, requestId); return { tabId: tab.id, url: safeBrowserUrl(final.url), title: await page.title() }; } finally { await page.unroute("**/*", guard); } }
  async inspect(tabId?: unknown) { const tab = this.tab(tabId); const origin = this.observed(tab); const page = tab.page; const snapshot = await page.evaluate(() => { const visible = (e: Element) => { const r = e.getBoundingClientRect(); const s = getComputedStyle(e); return r.width > 0 && r.height > 0 && s.visibility !== "hidden" && s.display !== "none"; }; const name = (e: Element) => (e.getAttribute("aria-label") || (e instanceof HTMLInputElement ? e.labels?.[0]?.textContent : "") || e.textContent || "").trim().replace(/\s+/g, " ").slice(0, 160); return { readyState: document.readyState, headings: [...document.querySelectorAll("h1,h2,h3")].filter(visible).slice(0, 50).map(e => ({ level: e.tagName.toLowerCase(), text: name(e) })), landmarks: [...document.querySelectorAll("main,nav,header,footer,aside,[role=main],[role=navigation]")].filter(visible).slice(0, 30).map(e => ({ role: e.getAttribute("role") || e.tagName.toLowerCase(), name: name(e) })), elements: [...document.querySelectorAll("button,a,input,select,textarea,[role=button],[role=link]")].filter(visible).slice(0, 200).map((e, index) => ({ index, tag: e.tagName.toLowerCase(), role: e.getAttribute("role") || (e.tagName === "A" ? "link" : e.tagName === "BUTTON" ? "button" : ""), name: name(e), fieldName: e.getAttribute("name") || "", type: e.getAttribute("type") || "", href: e.getAttribute("href") || "", testId: e.getAttribute("data-testid") || "", id: e.id || "", aria: e.getAttribute("aria-describedby") || "" })) }; });
    tab.refs.clear(); const elements = snapshot.elements.map(e => { const label = cleanLabel(e.name); const intent = `${label} ${e.href} ${e.fieldName} ${e.id}`; const strategy: Ref["strategy"] = e.role && label ? "role" : ["input", "select", "textarea"].includes(e.tag) && label ? "label" : label ? "text" : e.testId ? "testid" : "css"; const ref: Ref = { id: randomUUID(), tabId: tab.id, revision: tab.revision, kind: e.tag, marker: String(e.index), strategy, role: e.role, testId: e.testId, selector: `[data-freeos-ref="${e.index}"]`, label, sensitive: sensitive.test(`${label} ${e.type} ${e.fieldName} ${e.id}`), financial: financial.test(`${label} ${e.type} ${e.fieldName} ${e.id}`), intent }; tab.refs.set(ref.id, ref); return { refId: ref.id, strategy, ...e, href: e.href ? safeBrowserUrl(new URL(e.href, page.url()).href) : "", sensitive: ref.sensitive, financial: ref.financial }; });
    // Indexes come from the same visible DOM selection; annotate only elements we inspected.
    await page.evaluate(() => { const visible = (e: Element) => { const r = e.getBoundingClientRect(); const s = getComputedStyle(e); return r.width > 0 && r.height > 0 && s.visibility !== "hidden" && s.display !== "none"; }; [...document.querySelectorAll("button,a,input,select,textarea,[role=button],[role=link]")].filter(visible).slice(0, 200).forEach((e, i) => e.setAttribute("data-freeos-ref", String(i))); });
    return { tabId: tab.id, url: safeBrowserUrl(page.url()), title: await page.title(), origin, readyState: snapshot.readyState, headings: snapshot.headings, landmarks: snapshot.landmarks, buttons: elements.filter(e => e.tag === "button" || e.role === "button"), links: elements.filter(e => e.tag === "a" || e.role === "link"), inputs: elements.filter(e => ["input", "textarea", "select"].includes(e.tag)), elements };
  }
  async text(tabId?: unknown) { const tab = this.tab(tabId); this.observed(tab); const max = bounded("BROWSER_MAX_TEXT_CHARS", 50000, 200000); const value = await tab.page.locator("body").innerText({ timeout: bounded("BROWSER_DEFAULT_TIMEOUT_MS", 30000, 120000) }); return { tabId: tab.id, text: value.slice(0, max), truncated: value.length > max }; }
  async links(tabId?: unknown) { const result = await this.inspect(tabId); return { tabId: result.tabId, links: result.links.slice(0, 100).map(e => ({ refId: e.refId, text: e.name, href: e.href })) }; }
  async forms(tabId?: unknown) { const tab = this.tab(tabId); this.observed(tab); const result = await this.inspect(tab.id); const forms = await tab.page.locator("form").evaluateAll(forms => forms.slice(0, 30).map((form, index) => ({ index, action: (form as HTMLFormElement).action, method: (form as HTMLFormElement).method, fields: [...form.querySelectorAll("input,select,textarea")].map(e => ({ name: e.getAttribute("name") || "", type: e.getAttribute("type") || e.tagName.toLowerCase(), label: e.getAttribute("aria-label") || "", sensitive: /password|secret|token|key|card|cvv|cvc|bank|routing|ssn/i.test(`${e.getAttribute("name")} ${e.getAttribute("type")} ${e.getAttribute("aria-label")}`) })) }))); return { tabId: tab.id, forms: forms.map(f => ({ ...f, action: safeBrowserUrl(f.action) })), inputs: result.inputs }; }
  async formPreview(tabId: unknown, refId: unknown) { const { tab, ref, locator } = this.target(tabId, refId); await this.currentTarget(ref, locator); const form = locator.locator("xpath=ancestor::form[1]"); if (await form.count() !== 1) throw new BrowserError("Submit control is not inside a form.", "validation"); const summary = await form.evaluate(element => { const f = element as HTMLFormElement; return { action: f.action, method: f.method, fields: [...f.querySelectorAll("input,select,textarea")].map(e => ({ name: e.getAttribute("name") || "", type: e.getAttribute("type") || e.tagName.toLowerCase(), value: /password|secret|token|key|card|cvv|cvc|bank|routing|ssn/i.test(`${e.getAttribute("name")} ${e.getAttribute("type")}`) ? "[redacted]" : "[not shown]" })) }; }); const target = normalizeUrl(summary.action); if (dangerous.test(`${ref.label} ${summary.action}`) || financial.test(`${ref.label} ${summary.action}`) || summary.fields.some(field => financial.test(`${field.name} ${field.type}`.replace(/[_-]/g, " ")))) throw new BrowserError("High-impact form submission is blocked."); this.requireOrigin(target.origin, "navigate"); ref.formPreview = { origin: normalizeUrl(tab.page.url()).origin, action: safeBrowserUrl(target.url), method: summary.method, fields: summary.fields, submitButton: ref.label, requiresApproval: true }; return ref.formPreview; }
  cachedFormPreview(tabId: unknown, refId: unknown) { const { ref } = this.target(tabId, refId); if (!ref.formPreview) throw new BrowserError("Preview the form before creating a submit request.", "blocked"); return ref.formPreview; }
  elements(tabId?: unknown) { return this.inspect(tabId).then(r => ({ tabId: r.tabId, elements: r.elements })); }
  private target(tabId: unknown, refId: unknown): { tab: Tab; ref: Ref; locator: Locator } { const tab = this.tab(tabId); this.observed(tab); if (typeof refId !== "string") throw new BrowserError("Inspected element reference required.", "validation"); const ref = tab.refs.get(refId); if (!ref || ref.revision !== tab.revision) throw new BrowserError("Element reference is stale; inspect the page again."); const locator = ref.strategy === "role" ? tab.page.getByRole(ref.role as "button", { name: ref.label, exact: true }) : ref.strategy === "label" ? tab.page.getByLabel(ref.label, { exact: true }) : ref.strategy === "text" ? tab.page.getByText(ref.label, { exact: true }) : ref.strategy === "testid" ? tab.page.getByTestId(ref.testId) : tab.page.locator(ref.selector); return { tab, ref, locator }; }
  private async currentTarget(ref: Ref, locator: Locator) { if (await locator.count() !== 1 || await locator.getAttribute("data-freeos-ref") !== ref.marker) throw new BrowserError("Element reference changed; inspect the page again."); }
  validateAction(key: string, args: Record<string, unknown>) { if (!actionKeys.has(key)) throw new BrowserError("Unsupported browser action.", "blocked"); if (key === "browser.navigate") { const t = normalizeUrl(args.url); this.requireOrigin(t.origin, "navigate"); return { url: t.url, origin: t.origin }; } if (key === "browser.download") throw new BrowserError("Downloads are unavailable in this foundation."); const { tab, ref } = this.target(args.tabId, args.refId); this.control(); this.requireOrigin(normalizeUrl(tab.page.url()).origin, "interact"); if (dangerous.test(ref.intent)) throw new BrowserError("High-impact browser action is blocked."); if (ref.financial) throw new BrowserError("Financial and payment fields are blocked."); if (key === "browser.input" && (typeof args.value !== "string" || args.value.length > 10000)) throw new BrowserError("Input value must be bounded text.", "validation"); if (key === "browser.form.submit" && !["button", "input"].includes(ref.kind)) throw new BrowserError("Submit requires an inspected submit control.", "validation"); return { tabId: tab.id, refId: ref.id, label: ref.label, sensitive: ref.sensitive }; }
  async action(key: string, args: Record<string, unknown>, requestId?: number) { const preview = this.validateAction(key, args); if (key === "browser.navigate") return this.navigate(args.url, args.tabId, requestId); const { tab, ref, locator } = this.target(args.tabId, args.refId); await this.currentTarget(ref, locator); if (key === "browser.click" && (/submit|send|publish|buy|pay/i.test(ref.label) || (await locator.getAttribute("type")) === "submit")) throw new BrowserError("Use browser.form.submit for submit controls."); if (key === "browser.form.submit") { const type = await locator.getAttribute("type"); if (type !== "submit" && !/submit/i.test(ref.label)) throw new BrowserError("Target is not a submit control."); await this.formPreview(args.tabId, args.refId); await locator.click(); } else if (key === "browser.click") await locator.click(); else if (key === "browser.input") await locator.fill(String(args.value)); else if (key === "browser.select") { if (typeof args.value !== "string") throw new BrowserError("Select value required.", "validation"); await locator.selectOption(args.value); } else if (key === "browser.check") await locator.check(); else if (key === "browser.uncheck") await locator.uncheck(); else throw new BrowserError("Unsupported browser action."); this.record(key, tab.page, requestId); return { action: key, tabId: tab.id, refId: ref.id, url: safeBrowserUrl(tab.page.url()), value: key === "browser.input" ? "[redacted]" : undefined, preview }; }
  async screenshot(tabId?: unknown) { this.enabled(); if (!bool("BROWSER_SCREENSHOT_ENABLED", true)) throw new BrowserError("Browser screenshots disabled."); const tab = this.tab(tabId); this.observed(tab); safeDirectory(this.root, "data/browser/screenshots", "data/browser/screenshots"); mkdirSync(this.screenshotDir, { recursive: true }); const name = `freeos-browser-${Date.now()}-${randomUUID()}.png`; await tab.page.screenshot({ path: join(this.screenshotDir, name), timeout: bounded("BROWSER_DEFAULT_TIMEOUT_MS", 30000, 120000) }); this.session?.screenshots.push(name); this.persist(); const files = readdirSync(this.screenshotDir).filter(n => /^freeos-browser-\d+-[0-9a-f-]+\.png$/.test(n)).sort(); for (const old of files.slice(0, Math.max(0, files.length - 20))) { safeDirectory(this.root, "data/browser/screenshots", "data/browser/screenshots"); const path = join(this.screenshotDir, old); const info = lstatSync(path); if (info.isFile() && !info.isSymbolicLink() && info.nlink === 1) unlinkSync(path); } return { tabId: tab.id, path: `data/browser/screenshots/${name}` }; }
  screenshotHistory() { return this.session?.screenshots.map(name => ({ path: `data/browser/screenshots/${name}` })) ?? []; }
}

export const browser = new BrowserOperator();
export async function executeBrowserTool(key: string, args: Record<string, unknown> = {}, audit: { requestId?: number } = {}) { if (!readKeys.has(key) && !actionKeys.has(key)) throw new BrowserError("Unknown browser tool.", "blocked"); switch (key) { case "browser.status": return browser.status(); case "browser.sessions.list": return browser.sessions(); case "browser.session.start": return browser.start(); case "browser.session.stop": return browser.stop(); case "browser.tabs.list": return browser.tabsList(); case "browser.navigation.preview": return browser.preview(args.url); case "browser.form.preview": return browser.formPreview(args.tabId, args.refId); case "browser.page.inspect": return browser.inspect(args.tabId); case "browser.page.text": return browser.text(args.tabId); case "browser.page.links": return browser.links(args.tabId); case "browser.page.forms": return browser.forms(args.tabId); case "browser.page.elements": return browser.elements(args.tabId); case "browser.page.screenshot": return browser.screenshot(args.tabId); default: return browser.action(key, args, audit.requestId); } }
export function browserAuditArgs(key: string, args: Record<string, unknown>) { if (key === "browser.input" || key === "browser.select") return { tabId: args.tabId, refId: args.refId, value: "[redacted]" }; if (key === "browser.navigate") return { tabId: args.tabId, url: safeBrowserUrl(args.url) }; return args; }
