import { type FormEvent, useCallback, useEffect, useState } from "react";
import { api, type AutomationRule, type AutomationStatus, type ToolDefinition } from "../lib/api";

const field = "w-full border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-slate-200 outline-none focus:border-signal/40";
const button = "border border-electric/30 bg-electric/10 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.13em] text-electric hover:bg-electric/15 disabled:opacity-40";

export function AutomationPanel() {
  const [status, setStatus] = useState<AutomationStatus | null>(null); const [rules, setRules] = useState<AutomationRule[]>([]); const [tools, setTools] = useState<ToolDefinition[]>([]); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const [draft, setDraft] = useState({ ruleKey: "", name: "", description: "", triggerType: "manual" as "manual" | "interval_preview", actionToolKey: "", actionArgs: "{}" });
  const refresh = useCallback(async () => { const [s, r, t] = await Promise.all([api.automationsStatus(), api.automations(), api.tools()]); setStatus(s); setRules(r); setTools(t); setDraft((value) => ({ ...value, actionToolKey: value.actionToolKey || t.find((tool) => tool.enabled)?.toolKey || "" })); }, []);
  useEffect(() => { refresh().catch((error) => setNotice(error instanceof Error ? error.message : "Automation data unavailable.")); }, [refresh]);
  async function action(operation: () => Promise<unknown>, message: string) { setBusy(true); setNotice(null); try { await operation(); setNotice(message); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "Automation action failed."); } finally { setBusy(false); } }
  function submit(event: FormEvent) { event.preventDefault(); void action(async () => { const parsed: unknown = JSON.parse(draft.actionArgs || "{}"); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("Action args must be a JSON object."); await api.createAutomation({ ...draft, actionArgs: parsed as Record<string, unknown> }); }, "Manual automation rule created disabled by default."); }
  return <section className="mt-4 border border-white/10 bg-panel/80 p-6 lg:p-8"><p className="m-0 text-[10px] font-bold uppercase tracking-[.24em] text-electric">Preview and manual only</p><h2 className="mb-0 mt-2 text-2xl font-semibold text-white">Local automations</h2><p className="mb-0 mt-2 text-sm text-slate-500">Phase 5 has no background scheduler. Write actions become approval requests, never automatic execution.</p>
    {notice && <div className="mt-4 border border-white/10 bg-black/20 px-4 py-3 text-sm text-slate-300">{notice}</div>}
    <div className="mt-6 grid gap-3 sm:grid-cols-4">{[["Automations", status?.automationsEnabled ? "Enabled" : "—"], ["Rules", status?.rulesCount ?? "—"], ["Enabled rules", status?.enabledRulesCount ?? "—"], ["Dangerous actions", "Disabled"]].map(([label, value]) => <div key={label} className="border border-white/[.07] bg-white/[.02] p-3"><p className="m-0 text-[9px] uppercase tracking-[.16em] text-slate-600">{label}</p><p className="mb-0 mt-2 font-mono text-sm text-slate-200">{value}</p></div>)}</div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div><h3 className="text-sm uppercase tracking-[.16em] text-slate-300">Automation rules</h3><div className="space-y-2">{rules.length === 0 && <p className="text-sm text-slate-600">No rules yet.</p>}{rules.map((rule) => <article key={rule.ruleKey} className="border border-white/[.07] bg-black/10 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="m-0 text-sm font-semibold text-white">{rule.name}</p><p className="mb-0 mt-1 font-mono text-[10px] text-slate-600">{rule.ruleKey} · {rule.triggerType} · {rule.actionToolKey}</p></div><span className={`text-[10px] uppercase ${rule.enabled ? "text-signal" : "text-slate-600"}`}>{rule.enabled ? "enabled" : "disabled"}</span></div><p className="mb-0 mt-2 text-xs text-slate-500">{rule.description || "No description."}</p><div className="mt-3 flex gap-2"><button className={button} disabled={busy} onClick={() => void action(() => api.setAutomationEnabled(rule.ruleKey, !rule.enabled), `Rule ${rule.enabled ? "disabled" : "enabled"}.`)}>{rule.enabled ? "Disable" : "Enable"}</button><button className={button} disabled={busy || !rule.enabled} onClick={() => void action(() => api.checkAutomation(rule.ruleKey), rule.requiresApproval ? "Check created an approval request. No action ran." : "Read-only check completed.")}>Run check</button></div></article>)}</div></div>
      <form onSubmit={submit} className="space-y-3 border border-white/[.07] p-4"><h3 className="mt-0 text-sm uppercase tracking-[.16em] text-slate-300">Create manual rule</h3><input className={field} required placeholder="rule.key" value={draft.ruleKey} onChange={(event) => setDraft({ ...draft, ruleKey: event.target.value })}/><input className={field} required placeholder="Rule name" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })}/><input className={field} placeholder="Description" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })}/><select className={field} value={draft.triggerType} onChange={(event) => setDraft({ ...draft, triggerType: event.target.value as typeof draft.triggerType })}><option value="manual">Manual</option><option value="interval_preview">Interval preview (manual check)</option></select><select className={field} value={draft.actionToolKey} onChange={(event) => setDraft({ ...draft, actionToolKey: event.target.value })}>{tools.filter((tool) => tool.enabled).map((tool) => <option key={tool.toolKey} value={tool.toolKey}>{tool.name}</option>)}</select><textarea className={`${field} min-h-28 font-mono text-xs`} value={draft.actionArgs} onChange={(event) => setDraft({ ...draft, actionArgs: event.target.value })}/><button className={button} disabled={busy}>Create disabled rule</button></form></div>
  </section>;
}
