import { useCallback, useEffect, useState } from "react";
import { api, type BackupStatus, type CommandStatus } from "../lib/api";

export function BackupPanel({ status }: { status: CommandStatus | null }) {
  const [backups, setBackups] = useState<BackupStatus | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [options, setOptions] = useState({ includeDatabase: true, includeProjects: true, includeDocs: true, includeLogs: false });
  const refresh = useCallback(async () => setBackups(await api.backupStatus()), []); useEffect(() => { void refresh(); }, [refresh]);
  async function create() { setBusy(true); setMessage(null); try { await api.createBackup(options); await refresh(); setMessage("Safe local backup created."); } catch (error) { setMessage(error instanceof Error ? error.message : "Backup failed."); } finally { setBusy(false); } }
  return <div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><section className="panel"><p className="eyebrow">Environment</p><h2 className="section-title">Local settings</h2><dl className="mt-5 space-y-3 text-xs">{[["Database", status?.memory.databasePath], ["Project root", "data/projects"], ["SearXNG", status?.research.searxngBaseUrl], ["Ollama", "http://localhost:11434"], ["Voice recordings", status?.voice.recordingsDir], ["Voice output", status?.voice.outputDir]].map(([label, value]) => <div key={label}><dt className="meta mt-0">{label}</dt><dd className="m-0 break-all font-mono text-slate-400">{value ?? "Unavailable"}</dd></div>)}</dl></section><section className="panel"><p className="eyebrow">Safe export</p><h2 className="section-title">Backup FREEOS</h2><p className="section-copy">Timestamped, non-overwriting, and additive. Secrets, dependencies, model files, and generated voice audio stay out.</p><div className="mt-5 flex flex-wrap gap-4">{Object.entries(options).map(([key, value]) => <label key={key} className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={value} onChange={(event) => setOptions((current) => ({ ...current, [key]: event.target.checked }))} />{key.replace("include", "")}</label>)}</div><button className="button mt-5" disabled={busy} onClick={() => void create()}>{busy ? "Creating backup…" : "Create safe backup"}</button>{message && <p className="notice">{message}</p>}<div className="mt-6 space-y-2"><p className="meta">Recent backups · {backups?.backupRoot ?? "exports/backups"}</p>{backups?.recentBackups.map((item) => <div key={item.path} className="queue-item flex justify-between gap-3"><span className="font-mono text-xs text-slate-400">{item.name}</span><span className="badge badge-ok">Manifest</span></div>)}{!backups?.recentBackups.length && <div className="empty">No backups yet.</div>}</div></section></div>;
}
