import { useEffect, useState } from "react";
import { api } from "../lib/api";
import { ApprovalHub } from "./ApprovalHub";

type Element = { refId: string; tag: string; name: string; type: string; sensitive: boolean };
type Inspection = { tabId: string; url: string; title: string; origin: string; headings: Array<{text:string}>; elements: Element[] };
type Status = { enabled: boolean; controlEnabled: boolean; screenshotEnabled: boolean; downloadsEnabled: boolean; engine: string | null; preferredEngine: string; activeEngine: string | null; browserDetected: boolean; executableDetected: boolean; profilePath: string; profilePersistent: boolean; profileIsolated: boolean; activeSession: string | null; permissions: Array<{origin:string; permissions:string[]; enabled:boolean}> };
export function BrowserPanel() {
  const [status, setStatus] = useState<Status | null>(null), [tabs, setTabs] = useState<Array<{id:string;url:string}>>([]), [sessions, setSessions] = useState<unknown[]>([]);
  const [url, setUrl] = useState(""), [preview, setPreview] = useState<unknown>(null), [inspection, setInspection] = useState<Inspection | null>(null), [detail, setDetail] = useState<unknown>(null);
  const [refId, setRefId] = useState(""), [kind, setKind] = useState("browser.click"), [value, setValue] = useState(""), [formReady, setFormReady] = useState(false), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [queue, setQueue] = useState(0);
  const read = async (key: string, args: Record<string, unknown> = {}) => (await api.runReadonlyTool(key, args)).output;
  async function refresh() { const [s, t, h] = await Promise.all([read("browser.status"), read("browser.tabs.list"), read("browser.sessions.list")]); setStatus(s as Status); setTabs(t as Array<{id:string;url:string}>); setSessions(h as unknown[]); }
  useEffect(() => { void work(refresh); }, []);
  async function work(fn: () => Promise<void>) { setBusy(true); setNotice(""); try { await fn(); } catch (error) { setNotice(error instanceof Error ? error.message : "Browser operation failed."); } finally { setBusy(false); } }
  async function request(key: string, args: Record<string, unknown>) { const item = await api.createToolRequest({ toolKey: key, title: `${key} on ${inspection?.origin || url}`, description: "Explicit Browser Operator action", args }); setNotice(`Request #${item.id} created. Review and approve it below.`); setQueue(n => n + 1); }
  const tabId = inspection?.tabId || tabs[0]?.id;
  return <div className="space-y-4">
    <section className="panel"><p className="eyebrow">BROWSER OPERATOR</p><h2 className="section-title">Observe → Navigate → Inspect → Prepare → Approve → Execute → Verify → Audit</h2><p className="notice">BROWSER ACTIONS REQUIRE EXPLICIT PERMISSION</p><p className="text-sm text-amber-300">PURCHASES, FINANCIAL ACTIONS, MESSAGING, AND PUBLISHING ARE NOT AUTHORIZED BY GENERAL BROWSER CONTROL</p>{notice && <p className="notice" role="status">{notice}</p>}</section>
    <div className="grid gap-4 xl:grid-cols-2"><section className="panel"><p className="eyebrow">Status</p><p className="meta">Enabled: {String(status?.enabled ?? false)} · Control: {String(status?.controlEnabled ?? false)} · Screenshots: {String(status?.screenshotEnabled ?? false)} · Downloads: {String(status?.downloadsEnabled ?? false)}</p><p className="meta">Browser engine: {status?.activeEngine === "chrome" ? "Google Chrome" : status?.activeEngine === "edge" ? "Microsoft Edge" : "Unavailable"} · Preferred engine: {status?.preferredEngine === "edge" ? "Edge" : "Chrome"} · Session: {status?.activeSession || "None"}</p><p className="meta">Profile: FREEOS isolated persistent profile ({status?.profilePath || "data/browser/profile"})</p><div className="mt-3 flex gap-2"><button className="button" disabled={busy} onClick={() => void work(async () => { await read("browser.session.start"); await refresh(); })}>Start session</button><button className="button" disabled={busy || !status?.activeSession} onClick={() => void work(async () => { await read("browser.session.stop"); setInspection(null); await refresh(); })}>Stop session</button><button className="button" onClick={() => void work(refresh)}>Refresh</button></div></section><section className="panel"><p className="eyebrow">Site permissions</p>{status?.permissions.map(p => <div className="queue-item" key={p.origin}><p className="text-sm">{p.origin}</p><p className="meta">{p.enabled ? p.permissions.join(", ") : "Disabled"}</p></div>)}{!status?.permissions.length && <p className="meta">No configured origins. Localhost observation and navigation are allowed.</p>}</section></div>
    <section className="panel"><p className="eyebrow">Session and tabs</p><p className="meta">{sessions.length} session(s)</p>{tabs.map(t => <p className="meta" key={t.id}>{t.id}: {t.url}</p>)}{!tabs.length && <p className="meta">No FREEOS browser tabs.</p>}</section>
    <section className="panel"><p className="eyebrow">Navigate</p><input className="field mt-3" type="url" placeholder="https://example.com" value={url} onChange={e => { setUrl(e.target.value); setPreview(null); }} /><div className="mt-3 flex gap-2"><button className="button" disabled={busy || !url} onClick={() => void work(async () => setPreview(await read("browser.navigation.preview", {url})))}>Preview</button><button className="button" disabled={busy || !preview || !status?.controlEnabled} onClick={() => void work(() => request("browser.navigate", {url, tabId}))}>Request navigation approval</button></div>{preview !== null && <pre className="mt-3 whitespace-pre-wrap text-xs">{JSON.stringify(preview, null, 2)}</pre>}</section>
    <div className="grid gap-4 xl:grid-cols-2"><section className="panel"><p className="eyebrow">Inspect</p><div className="mt-3 flex flex-wrap gap-2"><button className="button" disabled={busy || !tabId} onClick={() => void work(async () => { const data = await read("browser.page.inspect", {tabId}) as Inspection; setInspection(data); setRefId(data.elements[0]?.refId || ""); setFormReady(false); })}>Inspect page</button>{["text", "links", "forms", "screenshot"].map(x => <button key={x} className="button" disabled={busy || !tabId || (x === "screenshot" && !status?.screenshotEnabled)} onClick={() => void work(async () => setDetail(await read(`browser.page.${x}`, {tabId})))}>{x}</button>)}</div>{inspection && <div className="mt-3"><p className="text-sm text-white">{inspection.title}</p><p className="meta">{inspection.url}</p><p className="meta">{inspection.headings.map(h => h.text).join(" · ")}</p><div className="max-h-80 overflow-auto">{inspection.elements.map(e => <p className="meta" key={e.refId}>{e.tag} {e.name || e.type} · {e.refId.slice(0, 8)}{e.sensitive ? " · sensitive" : ""}</p>)}</div></div>}</section><section className="panel"><p className="eyebrow">Structured actions</p><p className="section-copy">Select an inspected element. Filling and submitting are separate requests.</p><select className="field mt-3" value={refId} onChange={e => { setRefId(e.target.value); setFormReady(false); }}><option value="">Select element</option>{inspection?.elements.map(e => <option key={e.refId} value={e.refId}>{e.tag}: {e.name || e.type} ({e.refId.slice(0, 8)})</option>)}</select><select className="field mt-2" value={kind} onChange={e => { setKind(e.target.value); setFormReady(false); }}>{["browser.click", "browser.input", "browser.select", "browser.check", "browser.uncheck", "browser.form.submit"].map(x => <option key={x}>{x}</option>)}</select>{["browser.input", "browser.select"].includes(kind) && <input className="field mt-2" type={inspection?.elements.find(e => e.refId === refId)?.sensitive ? "password" : "text"} value={value} onChange={e => setValue(e.target.value)} placeholder="Value (never stored in audit)" />}<button className="button mt-3" disabled={busy || !refId || !status?.controlEnabled || (kind === "browser.form.submit" && !formReady)} onClick={() => void work(() => request(kind, {tabId: inspection?.tabId, refId, ...(["browser.input", "browser.select"].includes(kind) ? {value} : {})}))}>Create approval request</button></section></div>
    {kind === "browser.form.submit" && refId && <button className="button" onClick={() => void work(async () => { setFormReady(false); setDetail(await read("browser.form.preview", {tabId: inspection?.tabId, refId})); setFormReady(true); })}>Preview form submission</button>}
    {detail !== null && <section className="panel"><p className="eyebrow">Page result / screenshot history</p><pre className="max-h-80 overflow-auto whitespace-pre-wrap break-words text-xs">{JSON.stringify(detail, null, 2)}</pre></section>}
    <section className="panel"><p className="eyebrow">Audit</p><p className="meta">Review recent browser requests and runs in the approval queue.</p></section><ApprovalHub key={queue} onChanged={() => { void work(refresh); }} />
  </div>;
}
