import { useState, type FormEvent } from "react";
import { api, type Project } from "../lib/api";

export function ChatPanel({ projects, onApprovalCreated }: { projects: Project[]; onApprovalCreated?: () => void }) {
  const [message, setMessage] = useState(""); const [projectKey, setProjectKey] = useState(""); const [response, setResponse] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [options, setOptions] = useState({ useMemory: true, useProjectNotes: true, useResearchContext: false, allowToolSuggestions: true, speak: false });
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const result = await api.commandChat({ message, projectKey: projectKey || undefined, ...options }); setResponse(result.response); if (result.audioUrl) void new Audio(api.audioUrl(result.audioUrl)!).play(); if (result.createdMemoryProposalId || result.createdToolRequestId) onApprovalCreated?.(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Local chat failed."); } finally { setBusy(false); } }
  return <section className="panel"><p className="eyebrow">Local Ollama bridge</p><h2 className="section-title">Chat with free-os</h2><p className="section-copy">Approved memory only. No cloud providers. Chat can suggest or queue actions, but never executes them.</p>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1fr_.34fr]"><form onSubmit={submit} className="space-y-3"><textarea className="field min-h-40 resize-y" required value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Ask free-os to plan, explain, research, or organize…" /><button className="button" disabled={busy}>{busy ? "Thinking locally…" : "Send to local model"}</button></form><div className="space-y-3"><label className="label">Project context<select className="field mt-2" value={projectKey} onChange={(event) => setProjectKey(event.target.value)}><option value="">No project selected</option>{projects.map((project) => <option key={project.projectKey} value={project.projectKey}>{project.name}</option>)}</select></label>{Object.entries(options).map(([key, value]) => <label className="flex items-center gap-3 text-xs text-slate-400" key={key}><input type="checkbox" checked={value} onChange={(event) => setOptions((current) => ({ ...current, [key]: event.target.checked }))} /><span>{({ useMemory: "Use approved memory", useProjectNotes: "Use project notes", useResearchContext: "Use recent research", allowToolSuggestions: "Allow tool suggestions", speak: "Speak response locally" } as Record<string, string>)[key]}</span></label>)}</div></div>
    {error && <p className="notice">{error}</p>}{response && <div className="mt-6 border border-electric/20 bg-electric/[.03] p-5"><p className="meta mt-0 text-electric">free-os response</p><p className="mb-0 whitespace-pre-wrap text-sm leading-7 text-slate-300">{response}</p></div>}
  </section>;
}
