import { useState, type FormEvent } from "react";
import { api, type Project } from "../lib/api";

export function ChatPanel({ projects, onApprovalCreated }: { projects: Project[]; onApprovalCreated?: () => void }) {
  const [message, setMessage] = useState(""); const [projectKey, setProjectKey] = useState(""); const [responseText, setResponseText] = useState(""); const [responseDetails, setResponseDetails] = useState<{ ragUsed?: boolean; ragSources?: Array<{ documentPath: string; documentName: string; chunks: number[] }>; warnings?: string[]; memoryUsed?: boolean; projectNotesUsed?: boolean; } | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [options, setOptions] = useState({ useMemory: true, useProjectNotes: true, useResearchContext: false, allowToolSuggestions: true, speak: false, useRag: false });
  const [ragMode, setRagMode] = useState<"keyword" | "hybrid" | "embeddings">("keyword");
  const [ragTopK, setRagTopK] = useState(5);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const result = await api.commandChat({ message, projectKey: projectKey || undefined, ragMode, ragTopK, ...options }); setResponseText(result.response); setResponseDetails({ ragUsed: result.ragUsed, ragSources: result.ragSources ?? [], warnings: result.warnings ?? [], memoryUsed: result.memoryUsed, projectNotesUsed: result.projectNotesUsed }); if (result.audioUrl) void new Audio(api.audioUrl(result.audioUrl)!).play(); if (result.createdMemoryProposalId || result.createdToolRequestId) onApprovalCreated?.(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Local chat failed."); } finally { setBusy(false); } }
  return <section className="panel"><p className="eyebrow">Local Ollama bridge</p><h2 className="section-title">Chat with free-os</h2><p className="section-copy">Approved memory only. No cloud providers. Chat can suggest or queue actions, but never executes them.</p>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1fr_.34fr]"><form onSubmit={submit} className="space-y-3"><textarea className="field min-h-40 resize-y" required value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Ask free-os to plan, explain, research, or organize…" /><button className="button" disabled={busy}>{busy ? "Thinking locally…" : "Send to local model"}</button></form><div className="space-y-3"><label className="label">Project context<select className="field mt-2" value={projectKey} onChange={(event) => setProjectKey(event.target.value)}><option value="">No project selected</option>{projects.map((project) => <option key={project.projectKey} value={project.projectKey}>{project.name}</option>)}</select></label>{Object.entries(options).map(([key, value]) => <label className="flex items-center gap-3 text-xs text-slate-400" key={key}><input type="checkbox" checked={value} onChange={(event) => setOptions((current) => ({ ...current, [key]: event.target.checked }))} /><span>{({ useMemory: "Use approved memory", useProjectNotes: "Use project notes", useResearchContext: "Use recent research", allowToolSuggestions: "Allow tool suggestions", speak: "Speak response locally", useRag: "Use indexed documents / RAG" } as Record<string, string>)[key]}</span></label>)}{options.useRag && <><label className="label">RAG mode<select className="field mt-2" value={ragMode} onChange={(event) => setRagMode(event.target.value as "keyword" | "hybrid" | "embeddings") }><option value="keyword">keyword</option><option value="hybrid">hybrid</option><option value="embeddings">embeddings</option></select></label><label className="label">RAG topK<input className="field mt-2" type="number" min={1} max={20} value={ragTopK} onChange={(event) => setRagTopK(Math.max(1, Math.min(20, Number(event.target.value) || 5)))} /></label></>}</div></div>
    {error && <p className="notice">{error}</p>}{responseText && <div className="mt-6 border border-electric/20 bg-electric/[.03] p-5"><p className="meta mt-0 text-electric">free-os response</p><p className="mb-0 whitespace-pre-wrap text-sm leading-7 text-slate-300">{responseText}</p>{responseDetails && <div className="mt-4 rounded border border-slate-700 bg-slate-950/80 p-3 text-sm text-slate-300"><p className="text-xs uppercase tracking-[.2em] text-slate-500">Response metadata</p><p className="mt-2">Memory used: {responseDetails.memoryUsed ? "yes" : "no"}</p><p>Project notes used: {responseDetails.projectNotesUsed ? "yes" : "no"}</p><p>RAG used: {responseDetails.ragUsed ? "yes" : "no"}</p>{responseDetails.ragSources && responseDetails.ragSources.length > 0 && <div className="mt-2"><p className="font-semibold text-slate-200">RAG sources</p><ul className="list-disc pl-5 text-slate-300">{responseDetails.ragSources.map((source) => <li key={`${source.documentPath}-${source.chunks.length}`}>{source.documentName || source.documentPath} ({source.chunks.length} chunks)</li>)}</ul></div>}{responseDetails.warnings?.length ? <div className="mt-2 space-y-1 text-yellow-300">{responseDetails.warnings.map((warning) => <p key={warning}>{warning}</p>)}</div> : null}</div>}</div>}
  </section>;
}
