import { useEffect, useState } from "react";
import { api } from "../lib/api";
import { ApprovalHub } from "./ApprovalHub";

type Preview = { previewId: string; files: Array<{ path: string; operation: string; diff: string; oldSha256: string | null; newSha256: string }> };
type Session = { id: string; status: string; files: Array<{ path: string }> };
const commands = ["npm run build", "npm run build:api", "npm run build:dashboard", "npm run env:check", "npm run db:integrity", "npm run rag:status", "npm run computer:status", "npm run smoke:test", "npm run release:check", "npm run test:coding", "npm run test:computer", "git status --short", "git diff"];
export function CodingPanel() {
  const [roots, setRoots] = useState<string[]>([]), [root, setRoot] = useState(""), [path, setPath] = useState(""), [query, setQuery] = useState("");
  const [result, setResult] = useState<unknown>(null), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false);
  const [change, setChange] = useState('{"workspaceRoot":"E:\\\\FREEOS","summary":"Describe change","files":[]}'), [preview, setPreview] = useState<Preview | null>(null);
  const [command, setCommand] = useState(commands[0]), [commandReady, setCommandReady] = useState(false), [sessions, setSessions] = useState<Session[]>([]), [queue, setQueue] = useState(0);
  const read = async (key: string, args: Record<string, unknown> = {}) => (await api.runReadonlyTool(key, args)).output;
  async function act(fn: () => Promise<void>) { setBusy(true); setNotice(""); try { await fn(); } catch (e) { setNotice(e instanceof Error ? e.message : "Operation failed."); } finally { setBusy(false); } }
  async function refresh() { const list = await read("coding.workspaces.list") as Array<{ root: string }>; setRoots(list.map(w => w.root)); setRoot(r => r || list[0]?.root || ""); setSessions(await read("coding.sessions.list") as Session[]); }
  useEffect(() => { void act(refresh); }, []);
  async function request(key: string, args: Record<string, unknown>, title: string) { const item = await api.createToolRequest({ toolKey: key, title, args }); setNotice(`Request #${item.id} created. Review, approve, then run it below.`); setQueue(n => n + 1); }
  const show = (key: string, args: Record<string, unknown> = {}) => void act(async () => setResult(await read(key, { workspaceRoot: root, ...args })));
  return <div className="space-y-4">
    <section className="panel"><p className="eyebrow">SAFE CODING WORKSPACE</p><h2 className="section-title">Observe → Plan → Preview → Approve → Apply → Verify → Report</h2><p className="notice">CODING WRITES REQUIRE APPROVAL</p><p className="meta">Protected: registered roots, secrets, links, binaries, generated files. Workspace: {root || "Unavailable"}</p>{notice && <p className="notice" role="status">{notice}</p>}</section>
    <div className="grid gap-4 xl:grid-cols-2"><section className="panel"><p className="eyebrow">Workspace and Git</p><select className="field mt-3" value={root} onChange={e => setRoot(e.target.value)}>{roots.map(r => <option key={r}>{r}</option>)}</select><div className="mt-3 flex flex-wrap gap-2"><button className="button" disabled={busy} onClick={() => show("coding.workspace.inspect")}>Inspect</button><button className="button" disabled={busy} onClick={() => show("coding.git.status")}>Git status</button><button className="button" disabled={busy} onClick={() => show("coding.git.diff")}>Git diff</button></div></section><section className="panel"><p className="eyebrow">Read and search</p><input className="field mt-3" placeholder="Relative file path" value={path} onChange={e => setPath(e.target.value)} /><div className="mt-2 flex gap-2"><button className="button" disabled={busy || !path} onClick={() => show("coding.file.read", { path })}>Read file</button><button className="button" disabled={busy || !path} onClick={() => show("coding.git.diff_file", { path })}>File diff</button></div><input className="field mt-3" placeholder="Search source" value={query} onChange={e => setQuery(e.target.value)} /><button className="button mt-2" disabled={busy || !query} onClick={() => show("coding.search", { query })}>Search</button></section></div>
    {result !== null && <section className="panel"><p className="eyebrow">Inspection result</p><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words text-xs text-slate-300">{JSON.stringify(result, null, 2)}</pre></section>}
    <section className="panel"><p className="eyebrow">Change preview</p><p className="section-copy">Paste a structured change set. Updates require the SHA-256 returned by file read.</p><textarea className="field mt-3 min-h-48 font-mono text-xs" value={change} onChange={e => { setChange(e.target.value); setPreview(null); }} /><button className="button mt-2" disabled={busy} onClick={() => void act(async () => setPreview(await read("coding.change.preview", JSON.parse(change) as Record<string, unknown>) as Preview))}>Preview diff</button>{preview && <div className="mt-4 space-y-2"><p className="meta">Preview ID: {preview.previewId}</p>{preview.files.map(f => <div className="queue-item" key={f.path}><p>{f.operation.toUpperCase()} {f.path}</p><p className="meta">Before: {f.oldSha256 || "new"} · After: {f.newSha256}</p><pre className="max-h-96 overflow-auto whitespace-pre-wrap text-xs">{f.diff}</pre></div>)}<button className="button" onClick={() => void act(() => request("coding.change.apply", { previewId: preview.previewId }, `Apply coding preview ${preview.previewId}`))}>Create approval request</button></div>}</section>
    <div className="grid gap-4 xl:grid-cols-2"><section className="panel"><p className="eyebrow">Verify</p><select className="field mt-3" value={command} onChange={e => { setCommand(e.target.value); setCommandReady(false); }}>{commands.map(c => <option key={c}>{c}</option>)}</select><div className="mt-3 flex gap-2"><button className="button" disabled={busy} onClick={() => void act(async () => { setResult(await read("coding.command.preview", { workspaceRoot: root, command })); setCommandReady(true); })}>Preview command</button>{commandReady && <button className="button" onClick={() => void act(() => request("coding.command.run", { workspaceRoot: root, command }, `Run ${command}`))}>Create approval request</button>}</div></section><section className="panel"><p className="eyebrow">Sessions</p><button className="button mt-2" onClick={() => void act(refresh)}>Refresh sessions</button><div className="mt-3 space-y-2">{sessions.map(s => <div className="queue-item" key={s.id}><p className="text-sm">{s.id} · {s.status}</p><p className="meta">{s.files.map(f => f.path).join(", ")}</p>{s.status === "applied" && <button className="button" onClick={() => void act(() => request("coding.session.rollback", { sessionId: s.id }, `Rollback coding session ${s.id}`))}>Request rollback</button>}</div>)}{!sessions.length && <p className="meta">No sessions.</p>}</div></section></div>
    <ApprovalHub key={queue} onChanged={() => { void act(refresh); }} />
  </div>;
}
