import { type FormEvent, useCallback, useEffect, useState } from "react";
import { api, type PageRead, type Project, type ResearchResult, type ResearchSession, type ResearchStatus } from "../lib/api";

const fieldClass = "w-full border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-slate-200 outline-none transition placeholder:text-slate-700 focus:border-signal/40";
const buttonClass = "border border-signal/30 bg-signal/10 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.12em] text-signal transition hover:bg-signal/15 disabled:cursor-wait disabled:opacity-40";
const secondaryButton = "border border-white/10 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400 transition hover:border-white/20 hover:text-white disabled:opacity-40";
const explain = (error: unknown) => error instanceof Error ? error.message : "The local research request failed.";

function Heading({ eyebrow, title, detail }: { eyebrow: string; title: string; detail?: string }) {
  return <div><p className="m-0 text-[10px] font-bold uppercase tracking-[0.24em] text-electric">{eyebrow}</p><h2 className="mb-0 mt-2 text-xl font-semibold text-white">{title}</h2>{detail && <p className="mb-0 mt-2 text-sm leading-6 text-slate-500">{detail}</p>}</div>;
}

export function ResearchPanel({ projects, onMemoryChanged, onNoteChanged }: { projects: Project[]; onMemoryChanged: () => Promise<void>; onNoteChanged: (projectKey: string) => Promise<void> }) {
  const [status, setStatus] = useState<ResearchStatus | null>(null);
  const [sessions, setSessions] = useState<ResearchSession[]>([]);
  const [results, setResults] = useState<ResearchResult[]>([]);
  const [reader, setReader] = useState<PageRead | null>(null);
  const [query, setQuery] = useState("");
  const [projectKey, setProjectKey] = useState("");
  const [maxResults, setMaxResults] = useState(5);
  const [busy, setBusy] = useState<string | null>(null);
  const [feedback, setFeedback] = useState<{ error?: string; notice?: string }>({});

  const refreshStatus = useCallback(async () => {
    const settled = await Promise.allSettled([api.researchStatus(), api.researchSessions()]);
    if (settled[0].status === "fulfilled") setStatus(settled[0].value);
    if (settled[1].status === "fulfilled") setSessions(settled[1].value);
  }, []);
  useEffect(() => { void refreshStatus(); }, [refreshStatus]);

  async function search(event: FormEvent) {
    event.preventDefault(); setBusy("search"); setFeedback({}); setReader(null);
    try {
      const response = await api.researchSearch({ query, projectKey: projectKey || undefined, maxResults });
      setResults(response.results); setFeedback({ notice: `${response.results.length} research result${response.results.length === 1 ? "" : "s"} found and saved locally.` });
      await refreshStatus();
    } catch (error) { setFeedback({ error: explain(error) }); }
    finally { setBusy(null); }
  }

  async function loadSession(id: number) {
    setBusy(`session-${id}`); setFeedback({});
    try { const data = await api.researchSession(id); setResults(data.results); setQuery(data.session.query); setProjectKey(data.session.projectKey ?? ""); setReader(null); }
    catch (error) { setFeedback({ error: explain(error) }); } finally { setBusy(null); }
  }

  async function read(result: ResearchResult) {
    setBusy(`read-${result.id ?? result.url}`); setFeedback({});
    try { setReader(await api.readPage(result.url)); }
    catch (error) { setFeedback({ error: explain(error) }); } finally { setBusy(null); }
  }

  async function summarize(result: ResearchResult) {
    if (!result.id) return;
    setBusy(`summary-${result.id}`); setFeedback({});
    try {
      const updated = await api.summarizeResearchResult(result.id);
      setResults((current) => current.map((item) => item.id === updated.id ? updated : item));
      setReader({ title: updated.title, url: updated.url, domain: updated.domain, contentPreview: updated.contentPreview ?? updated.snippet, bytesRead: 0, summary: updated.summary ?? null, summaryMessage: null });
      setFeedback({ notice: "Summary generated by the configured local Ollama model." });
    } catch (error) { setFeedback({ error: explain(error) }); } finally { setBusy(null); }
  }

  async function createProposal(result: ResearchResult) {
    if (!result.id) return;
    setBusy(`proposal-${result.id}`); setFeedback({});
    try {
      await api.createResearchProposal(result.id, { projectKey: projectKey || undefined });
      setResults((current) => current.map((item) => item.id === result.id ? { ...item, savedAsMemoryProposalId: -1 } : item));
      await onMemoryChanged(); setFeedback({ notice: "Pending memory proposal created. It still requires your approval." });
    } catch (error) { setFeedback({ error: explain(error) }); } finally { setBusy(null); }
  }

  async function createNote(result: ResearchResult) {
    if (!result.id) return;
    if (!projectKey) { setFeedback({ error: "Choose a project before saving a research result as a project note." }); return; }
    setBusy(`note-${result.id}`); setFeedback({});
    try {
      await api.createResearchNote(result.id, { projectKey });
      setResults((current) => current.map((item) => item.id === result.id ? { ...item, savedAsProjectNoteId: -1 } : item));
      await onNoteChanged(projectKey); setFeedback({ notice: "Research result saved as an explicit local project note." });
    } catch (error) { setFeedback({ error: explain(error) }); } finally { setBusy(null); }
  }

  return <section className="mt-4 border border-white/10 bg-panel/80 p-6 lg:p-8">
    <Heading eyebrow="Phase 3 / Research" title="Local-first web research" detail="Search through your SearXNG instance, read public pages, summarize locally, and choose what becomes knowledge." />
    {feedback.error && <div className="mt-5 border border-red-400/25 bg-red-400/5 px-4 py-3 text-sm text-red-200">{feedback.error}</div>}
    {feedback.notice && <div className="mt-5 border border-signal/25 bg-signal/5 px-4 py-3 text-sm text-signal">{feedback.notice}</div>}
    <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
      <div className="border border-white/[0.07] bg-black/10 p-4"><p className="m-0 text-[9px] uppercase tracking-[0.18em] text-slate-600">SearXNG</p><p className={`mb-0 mt-2 font-mono text-sm ${status?.searxngOnline ? "text-signal" : "text-amber-300"}`}>{status?.searxngOnline ? "Online" : "Offline / setup needed"}</p><p className="mb-0 mt-2 break-all text-xs text-slate-600">{status?.searxngBaseUrl ?? "Checking configuration…"}</p></div>
      <div className="border border-white/[0.07] bg-black/10 p-4"><p className="m-0 text-[9px] uppercase tracking-[0.18em] text-slate-600">Local summarizer</p><p className={`mb-0 mt-2 font-mono text-sm ${status?.ollamaOnline ? "text-signal" : "text-amber-300"}`}>{status?.ollamaOnline ? "Ollama online" : "Ollama offline"}</p><p className="mb-0 mt-2 text-xs text-slate-600">{status?.defaultModel ?? "qwen3:8b"}</p></div>
      <div className="border border-white/[0.07] bg-black/10 p-4"><p className="m-0 text-[9px] uppercase tracking-[0.18em] text-slate-600">Research archive</p><p className="mb-0 mt-2 font-mono text-sm text-slate-300">{status?.counts.sessions ?? 0} sessions · {status?.counts.sources ?? 0} sources</p><p className="mb-0 mt-2 text-xs text-slate-600">Stored in local SQLite</p></div>
      <div className="border border-white/[0.07] bg-black/10 p-4"><p className="m-0 text-[9px] uppercase tracking-[0.18em] text-slate-600">External API keys</p><p className="mb-0 mt-2 font-mono text-sm text-signal">None required</p><p className="mb-0 mt-2 text-xs text-slate-600">Dangerous actions remain off</p></div>
    </div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1fr_.38fr]">
      <div><form onSubmit={search} className="grid gap-3 border border-white/[0.07] bg-white/[0.015] p-4 md:grid-cols-[1fr_14rem_7rem_auto]"><input className={fieldClass} required placeholder="Research query" value={query} onChange={(e) => setQuery(e.target.value)} /><select className={fieldClass} value={projectKey} onChange={(e) => setProjectKey(e.target.value)}><option value="">No project</option>{projects.map((project) => <option key={project.projectKey} value={project.projectKey}>{project.name}</option>)}</select><input className={fieldClass} type="number" min={1} max={20} value={maxResults} onChange={(e) => setMaxResults(Number(e.target.value))} /><button className={buttonClass} disabled={busy !== null || status?.searxngOnline === false}>Search web</button></form>
        <div className="mt-4 space-y-3">{results.length === 0 && <div className="border border-dashed border-white/10 px-4 py-10 text-center text-sm text-slate-600">No active research results.</div>}{results.map((result, index) => <article key={result.id ?? `${result.url}-${index}`} className="border border-white/[0.08] bg-black/10 p-4"><h3 className="m-0 text-sm font-semibold text-white">{result.title}</h3><p className="mb-0 mt-1 text-[10px] uppercase tracking-[0.14em] text-electric">{result.domain} · {result.source}</p><a href={result.url} target="_blank" rel="noreferrer" className="mt-2 block break-all text-xs text-slate-600 hover:text-slate-300">{result.url}</a><p className="mb-0 mt-3 text-sm leading-6 text-slate-400">{result.snippet || "No search snippet was provided."}</p>{result.summary && <p className="mb-0 mt-3 border-l-2 border-electric/30 pl-3 text-sm leading-6 text-slate-300">{result.summary}</p>}<div className="mt-4 flex flex-wrap gap-2"><button className={secondaryButton} disabled={busy !== null} onClick={() => void read(result)}>Read page</button><button className={secondaryButton} disabled={busy !== null || !result.id} onClick={() => void summarize(result)}>Summarize locally</button><button className={buttonClass} disabled={busy !== null || !result.id || Boolean(result.savedAsMemoryProposalId)} onClick={() => void createProposal(result)}>{result.savedAsMemoryProposalId ? "Proposal created" : "Create memory proposal"}</button><button className={secondaryButton} disabled={busy !== null || !result.id || Boolean(result.savedAsProjectNoteId)} onClick={() => void createNote(result)}>{result.savedAsProjectNoteId ? "Note saved" : "Save as project note"}</button></div></article>)}</div>
      </div>
      <aside className="space-y-4"><div className="border border-white/[0.07] bg-black/10 p-4"><p className="m-0 text-[10px] font-bold uppercase tracking-[0.18em] text-electric">Research history</p><div className="mt-3 space-y-2">{sessions.slice(0, 10).map((session) => <button key={session.id} disabled={busy !== null} onClick={() => void loadSession(session.id)} className="block w-full border border-white/[0.06] p-3 text-left hover:border-white/15"><span className="block text-xs text-slate-300">{session.query}</span><span className="mt-1 block font-mono text-[9px] text-slate-700">{session.resultCount ?? 0} results · {session.projectKey ?? "unassigned"}</span></button>)}{sessions.length === 0 && <p className="text-xs text-slate-600">No saved sessions yet.</p>}</div></div><div className="border border-white/[0.07] bg-black/10 p-4"><p className="m-0 text-[10px] font-bold uppercase tracking-[0.18em] text-electric">Page reader</p>{reader ? <div className="mt-3"><h3 className="m-0 text-sm text-white">{reader.title}</h3><p className="mt-1 text-[10px] text-slate-600">{reader.domain}</p>{reader.summary && <div className="mt-4"><p className="text-[9px] uppercase tracking-widest text-signal">Local summary</p><p className="whitespace-pre-wrap text-xs leading-5 text-slate-300">{reader.summary}</p></div>}<p className="mt-4 max-h-80 overflow-y-auto whitespace-pre-wrap text-xs leading-5 text-slate-500">{reader.contentPreview}</p><a href={reader.url} target="_blank" rel="noreferrer" className="mt-3 block break-all text-[10px] text-electric">Source URL</a></div> : <p className="mt-3 text-xs leading-5 text-slate-600">Choose Read page to extract a bounded preview from a public HTML page.</p>}</div></aside>
    </div>
  </section>;
}
