import { type FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { api, type ToolDefinition, type ToolRequest, type ToolRiskLevel, type ToolRun, type ToolStatus } from "../lib/api";

const field = "w-full border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-slate-200 outline-none focus:border-signal/40";
const button = "border border-signal/30 bg-signal/10 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.13em] text-signal hover:bg-signal/15 disabled:cursor-wait disabled:opacity-40";
const dangerButton = "border border-red-300/20 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.13em] text-red-200/80 hover:bg-red-300/5 disabled:opacity-40";
const risks: ToolRiskLevel[] = ["read_only", "low_risk_write", "medium_risk", "high_risk"];
const labels: Record<ToolRiskLevel, string> = { read_only: "Read only", low_risk_write: "Low-risk writes", medium_risk: "Medium risk · preview first", high_risk: "High risk · blocked" };
const emptyDraft = { toolKey: "", title: "", description: "", args: "{}" };
function pretty(value: unknown) { return JSON.stringify(value, null, 2); }
function parseArgs(value: string): Record<string, unknown> { const parsed: unknown = JSON.parse(value || "{}"); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("Args must be a JSON object."); return parsed as Record<string, unknown>; }

export function ToolRunnerPanel() {
  const [status, setStatus] = useState<ToolStatus | null>(null); const [tools, setTools] = useState<ToolDefinition[]>([]); const [requests, setRequests] = useState<ToolRequest[]>([]); const [runs, setRuns] = useState<ToolRun[]>([]);
  const [readKey, setReadKey] = useState(""); const [output, setOutput] = useState<unknown>(null); const [draft, setDraft] = useState(emptyDraft); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const refresh = useCallback(async () => { const [nextStatus, nextTools, nextRequests, nextRuns] = await Promise.all([api.toolsStatus(), api.tools(), api.toolRequests(), api.toolRuns()]); setStatus(nextStatus); setTools(nextTools); setRequests(nextRequests); setRuns(nextRuns); setReadKey((current) => current || nextTools.find((tool) => tool.riskLevel === "read_only" && tool.enabled)?.toolKey || ""); setDraft((current) => ({ ...current, toolKey: current.toolKey || nextTools.find((tool) => tool.riskLevel !== "read_only" && tool.enabled)?.toolKey || "" })); }, []);
  useEffect(() => { refresh().catch((error) => setMessage(error instanceof Error ? error.message : "Tool data unavailable.")); }, [refresh]);
  const writable = useMemo(() => tools.filter((tool) => tool.riskLevel !== "read_only"), [tools]);
  async function act(key: string, action: () => Promise<unknown>, notice: string) { setBusy(key); setMessage(null); try { setOutput(await action()); setMessage(notice); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Tool action failed."); } finally { setBusy(null); } }
  function submit(event: FormEvent) { event.preventDefault(); void act("create", () => api.createToolRequest({ toolKey: draft.toolKey, title: draft.title, description: draft.description, args: parseArgs(draft.args) }), "Tool request created. It has not run.").then(() => setDraft((value) => ({ ...emptyDraft, toolKey: value.toolKey }))); }
  return <section className="mt-4 border border-white/10 bg-panel/80 p-6 lg:p-8">
    <p className="m-0 text-[10px] font-bold uppercase tracking-[0.24em] text-electric">Phase 5 controls</p><h2 className="mb-0 mt-2 text-2xl font-semibold text-white">Safe tool runner</h2><p className="mb-0 mt-2 text-sm text-slate-500">Write/action tools require approval. High-risk tools are blocked.</p>
    {message && <div className="mt-4 border border-white/10 bg-black/20 px-4 py-3 text-sm text-slate-300">{message}</div>}
    <div className="mt-6 grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{[["Tools", status?.toolsEnabled ? "Enabled" : "—"], ["Registered", status?.registeredToolCount ?? "—"], ["Pending", status?.pendingToolRequestCount ?? "—"], ["Recent runs", status?.recentRunCount ?? "—"], ["Dangerous", "Disabled"], ["Paid keys", "None"]].map(([label, value]) => <div key={label} className="border border-white/[.07] bg-white/[.02] p-3"><p className="m-0 text-[9px] uppercase tracking-[.16em] text-slate-600">{label}</p><p className="mb-0 mt-2 font-mono text-sm text-slate-200">{value}</p></div>)}</div>
    <div className="mt-6 grid gap-5 xl:grid-cols-2">
      <div><h3 className="text-sm uppercase tracking-[.16em] text-slate-300">Tool registry</h3><div className="space-y-4">{risks.map((risk) => <div key={risk}><p className="text-[10px] font-bold uppercase tracking-[.16em] text-electric">{labels[risk]}</p><div className="space-y-2">{tools.filter((tool) => tool.riskLevel === risk).map((tool) => <article key={tool.toolKey} className="border border-white/[.07] bg-black/10 p-3"><div className="flex justify-between gap-3"><p className="m-0 text-sm font-semibold text-white">{tool.name}</p><span className={`text-[9px] uppercase ${tool.enabled ? "text-signal" : "text-red-300"}`}>{tool.enabled ? "enabled" : "blocked"}</span></div><p className="mb-0 mt-1 text-xs leading-5 text-slate-500">{tool.description}</p><p className="mb-0 mt-2 font-mono text-[9px] text-slate-600">{tool.toolKey} · {tool.category} · approval {tool.requiresApproval ? "required" : "not required"}</p></article>)}</div></div>)}</div></div>
      <div className="space-y-5"><div className="border border-white/[.07] p-4"><h3 className="mt-0 text-sm uppercase tracking-[.16em] text-slate-300">Run read-only tool</h3><select className={field} value={readKey} onChange={(event) => setReadKey(event.target.value)}>{tools.filter((tool) => tool.riskLevel === "read_only" && tool.enabled).map((tool) => <option key={tool.toolKey} value={tool.toolKey}>{tool.name}</option>)}</select><button className={`${button} mt-3`} disabled={!!busy || !readKey} onClick={() => void act("read", () => api.runReadonlyTool(readKey), "Read-only tool completed.")}>Run tool</button>{output !== null && <pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap border border-white/[.06] bg-black/30 p-3 text-[11px] text-slate-400">{pretty(output)}</pre>}</div>
      <form onSubmit={submit} className="space-y-3 border border-white/[.07] p-4"><h3 className="mt-0 text-sm uppercase tracking-[.16em] text-slate-300">Create tool request</h3><select className={field} value={draft.toolKey} onChange={(event) => setDraft({ ...draft, toolKey: event.target.value })}>{writable.map((tool) => <option key={tool.toolKey} value={tool.toolKey}>{tool.name} {tool.enabled ? "" : "(blocked)"}</option>)}</select><input className={field} required placeholder="Request title" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })}/><input className={field} placeholder="Description" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })}/><textarea className={`${field} min-h-32 font-mono text-xs`} value={draft.args} onChange={(event) => setDraft({ ...draft, args: event.target.value })}/><button className={button} disabled={!!busy}>Submit request</button></form></div>
    </div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><div><h3 className="text-sm uppercase tracking-[.16em] text-slate-300">Tool request queue</h3><div className="space-y-2">{requests.length === 0 && <p className="text-sm text-slate-600">Queue clear.</p>}{requests.map((item) => <article key={item.id} className="border border-white/[.07] bg-black/10 p-3"><div className="flex justify-between gap-3"><p className="m-0 text-sm font-semibold text-white">#{item.id} · {item.title}</p><span className="text-[10px] uppercase text-electric">{item.status}</span></div><p className="mb-0 mt-1 font-mono text-[10px] text-slate-600">{item.toolKey} · {item.riskLevel}</p><div className="mt-3 flex flex-wrap gap-2">{item.status === "pending" && <><button className={button} disabled={!!busy} onClick={() => void act(`approve-${item.id}`, () => api.approveToolRequest(item.id), "Request approved. It has not run yet.")}>Approve</button><button className={dangerButton} disabled={!!busy} onClick={() => void act(`reject-${item.id}`, () => api.rejectToolRequest(item.id), "Request rejected.")}>Reject</button></>}{item.status === "approved" && <button className={button} disabled={!!busy} onClick={() => void act(`run-${item.id}`, () => api.runToolRequest(item.id), "Approved tool request completed.")}>Run approved request</button>}</div></article>)}</div></div>
    <div><h3 className="text-sm uppercase tracking-[.16em] text-slate-300">Tool run history</h3><div className="space-y-2">{runs.length === 0 && <p className="text-sm text-slate-600">No runs yet.</p>}{runs.slice(0, 20).map((run) => <article key={run.id} className="border border-white/[.07] bg-black/10 p-3"><div className="flex justify-between"><p className="m-0 font-mono text-xs text-white">#{run.id} {run.toolKey}</p><span className="text-[9px] uppercase text-electric">{run.status}</span></div><p className="mb-0 mt-2 truncate text-xs text-slate-500">{run.error ?? pretty(run.output)}</p><p className="mb-0 mt-2 text-[9px] text-slate-700">{run.startedAt} → {run.finishedAt ?? "running"}</p></article>)}</div></div></div>
  </section>;
}
