import { createHash, randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { constants } from "node:fs";
import { access, lstat, mkdir, readFile, readdir, realpath, rename, rm, stat, writeFile } from "node:fs/promises";
import { basename, dirname, extname, isAbsolute, join, relative, resolve, sep } from "node:path";

const exec = promisify(execFile);
const hash = (value: Buffer | string) => createHash("sha256").update(value).digest("hex");
const DEFAULT_ROOT = "E:\\FREEOS";
const sourceExt = new Set([".ts", ".tsx", ".js", ".jsx", ".json", ".md", ".txt", ".css", ".html", ".yml", ".yaml", ".mjs", ".cjs", ".py", ".ps1", ".sql", ".sh", ".toml", ".xml", ".svg"]);
const blockedParts = new Set([".git", "node_modules", ".ssh", ".aws", ".azure", ".config", "appdata", "browser", "browsers", "profiles", "credentials", "secrets", "tokens", "models", "dist", "build", ".next", "coverage", "generated", "backups", "cache", ".cache", "vendor"]);
const blockedExt = new Set([".pem", ".key", ".p12", ".pfx", ".db", ".sqlite", ".bin", ".gguf", ".safetensors", ".onnx", ".pt", ".pth", ".exe", ".dll", ".png", ".jpg", ".jpeg", ".webp", ".zip", ".7z", ".pdf"]);
const safeScripts = new Set(["build", "build:api", "build:dashboard", "env:check", "db:integrity", "rag:status", "computer:status", "smoke:test", "release:check", "test", "test:coding", "test:computer"]);
export type ChangeFile = { path: string; operation: "create" | "update"; expectedSha256?: string; content: string };
export type ChangeSet = { workspaceRoot: string; summary: string; files: ChangeFile[] };
type Preview = { id: string; set: ChangeSet; expires: number; baselines: Array<{ path: string; sha256: string | null }> };
export class CodingError extends Error { constructor(message: string, readonly code: "blocked" | "validation" | "conflict" | "not_found" = "blocked") { super(message); this.name = "CodingError"; } }
const fail = (message: string, code: CodingError["code"] = "blocked"): never => { throw new CodingError(message, code); };
function max(name: string, fallback: number) { const n = Number(process.env[name]); return Number.isSafeInteger(n) && n > 0 ? n : fallback; }
function roots(): string[] { return (process.env.CODING_WORKSPACE_ROOTS || DEFAULT_ROOT).split(/[;,]/).map(s => resolve(s.trim())).filter(Boolean); }
function enabled() { return process.env.CODING_ENABLED !== "false"; }
function workspace(root: unknown): string { if (!enabled()) return fail("Coding is disabled."); if (typeof root !== "string" || !root || root.startsWith("\\\\") || root.includes("..")) return fail("Invalid workspace root."); const match = roots().find(r => r.toLowerCase() === resolve(root).toLowerCase()); if (!match) return fail("Workspace is not registered."); return match; }
function safeRelative(input: unknown): string { if (typeof input !== "string" || !input || isAbsolute(input) || input.startsWith("\\\\") || /^[a-z]:/i.test(input) || input.includes("\0")) return fail("Invalid relative path."); const parts = input.replace(/\\/g, "/").split("/"); if (parts.some(p => !p || p === "." || p === ".." || blockedParts.has(p.toLowerCase()) || p.toLowerCase().startsWith(".env") || /^(id_rsa|id_ed25519|credentials|secrets|tokens)/i.test(p)) || parts.slice(0,2).join("/").toLowerCase() === "exports/coding-sessions") return fail("Path is protected."); if (blockedExt.has(extname(input).toLowerCase())) return fail("File type is protected."); return parts.join("/"); }
async function pathIn(root: string, rel: unknown, create = false): Promise<string> { const clean = safeRelative(rel); const target = resolve(root, clean); if (!target.toLowerCase().startsWith((root + sep).toLowerCase())) return fail("Path escapes workspace."); const rootReal = await realpath(root); let cursor = root; const parts = clean.split("/"); for (let i = 0; i < parts.length; i++) { cursor = join(cursor, parts[i]); try { const s = await lstat(cursor); if (s.isSymbolicLink()) return fail("Symlinks are blocked."); if (i < parts.length - 1 && !s.isDirectory()) return fail("Parent is not a directory."); if (i === parts.length - 1 && !s.isFile()) return fail("Only regular files are allowed."); const actual = await realpath(cursor); if (!actual.toLowerCase().startsWith((rootReal + sep).toLowerCase())) return fail("Path escapes workspace."); } catch (e) { if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e; if (!create && i === parts.length - 1) return fail("File not found.", "not_found"); } } return target; }
async function textFile(path: string): Promise<{ content: string; sha256: string }> { const size = (await stat(path)).size; if (size > max("CODING_MAX_FILE_SIZE_KB", 1024) * 1024) return fail("File exceeds size limit."); const bytes = await readFile(path); if (bytes.includes(0)) return fail("Binary file blocked."); const content = new TextDecoder("utf-8", { fatal: true }).decode(bytes); return { content, sha256: hash(bytes) }; }
async function git(root: string, args: string[]) { try { const { stdout, stderr } = await exec("git", args, { cwd: root, windowsHide: true, timeout: 15000, maxBuffer: 2 * 1024 * 1024 }); return { stdout, stderr }; } catch { return { stdout: "", stderr: "Git unavailable or command failed." }; } }
async function countLanguages(root: string) { const counts: Record<string, number> = {}; let visited = 0; const walk = async (dir: string, depth: number): Promise<void> => { if (depth > 10 || visited > 10000) return; for (const item of await readdir(dir, { withFileTypes: true })) { if (visited++ > 10000) break; const path = relative(root, join(dir, item.name)).replace(/\\/g, "/"); try { safeRelative(path); } catch { continue; } if (item.isSymbolicLink()) continue; if (item.isDirectory()) { await walk(join(dir, item.name), depth + 1); continue; } const ext = extname(item.name).toLowerCase(); if (item.isFile() && sourceExt.has(ext)) counts[ext] = (counts[ext] || 0) + 1; } }; await walk(root, 0); return { counts, truncated: visited > 10000 }; }
export class CodingWorkspace {
  private previews = new Map<string, Preview>();
  constructor(readonly sessionBase = resolve(process.cwd(), "exports", "coding-sessions")) {}
  status() { return { enabled: enabled(), workspaces: enabled() ? roots() : [], approvalRequiredForWrites: true, approvalRequiredForCommands: true, protectedBoundaries: ["registered roots", "secrets", "symlinks", "binary files", "generated files"] }; }
  workspaces() { return enabled() ? roots().map(root => ({ root, name: basename(root) })) : []; }
  async inspect(input: { workspaceRoot: string }) { const root = workspace(input.workspaceRoot); const branch = (await git(root, ["branch", "--show-current"])).stdout.trim(); const dirty = !!(await git(root, ["status", "--short"])).stdout.trim(); const files = await readdir(root); const importantFiles = files.filter(f => ["package.json", "README.md", "tsconfig.json", "Cargo.toml", "pyproject.toml", "go.mod"].includes(f)); const packageManager = files.includes("package-lock.json") ? "npm" : files.includes("pnpm-lock.yaml") ? "pnpm" : files.includes("yarn.lock") ? "yarn" : null; return { root, repoName: basename(root), branch: branch || null, dirty, packageManager, importantFiles, languageFiles: await countLanguages(root) }; }
  async read(input: { workspaceRoot: string; path: string; startLine?: number; endLine?: number }) { const root = workspace(input.workspaceRoot); const path = await pathIn(root, input.path); const file = await textFile(path); const lines = file.content.split(/\r?\n/); const start = Math.max(1, Math.floor(input.startLine || 1)); const end = Math.min(lines.length, Math.floor(input.endLine || Math.min(start + 199, lines.length))); if (end < start || end - start > 999) return fail("Invalid line range.", "validation"); return { path: safeRelative(input.path), sha256: file.sha256, startLine: start, endLine: end, totalLines: lines.length, content: lines.slice(start - 1, end).join("\n") }; }
  async search(input: { workspaceRoot: string; query: string; maxResults?: number }) { const root = workspace(input.workspaceRoot); if (typeof input.query !== "string" || !input.query || input.query.length > 200) return fail("Invalid search query.", "validation"); const results: Array<{ path: string; line: number; text: string }> = []; const limit = Math.min(200, Math.max(1, input.maxResults || 100)); let scanned = 0; const walk = async (dir: string, depth: number): Promise<void> => { if (depth > 12 || results.length >= limit || scanned > 10000) return; for (const item of await readdir(dir, { withFileTypes: true })) { if (results.length >= limit) break; const rel = relative(root, join(dir, item.name)).replace(/\\/g, "/"); try { safeRelative(rel); } catch { continue; } if (item.isSymbolicLink()) continue; if (item.isDirectory()) { await walk(join(dir, item.name), depth + 1); continue; } if (!item.isFile() || !sourceExt.has(extname(item.name).toLowerCase())) continue; scanned++; try { const file = await textFile(await pathIn(root, rel)); file.content.split(/\r?\n/).forEach((line, i) => { if (results.length < limit && line.toLowerCase().includes(input.query.toLowerCase())) results.push({ path: rel, line: i + 1, text: line.slice(0, 300) }); }); } catch { /* skip protected/large/binary files */ } } }; await walk(root, 0); return { results, truncated: results.length >= limit }; }
  async gitStatus(input: { workspaceRoot: string }) { const root = workspace(input.workspaceRoot); const lines = (await git(root, ["status", "--short"])).stdout.split(/\r?\n/); return { status: lines.filter(line => { if (!line || line.includes(" -> ")) return false; try { safeRelative(line.slice(3)); return true; } catch { return false; } }).join("\n") }; }
  async gitDiff(input: { workspaceRoot: string; path?: string }) { const root = workspace(input.workspaceRoot); if (input.path !== undefined) { await pathIn(root, input.path); return { diff: (await git(root, ["diff", "--no-ext-diff", "--no-textconv", "--", safeRelative(input.path)])).stdout }; } const names = (await git(root, ["diff", "--name-only", "-z"])).stdout.split("\0").filter(Boolean); const diffs: string[] = []; for (const name of names.slice(0, 100)) { try { await pathIn(root, name); diffs.push((await git(root, ["diff", "--no-ext-diff", "--no-textconv", "--", safeRelative(name)])).stdout); } catch { /* protected path */ } } return { diff: diffs.join("\n") }; }
  async gitDiffFile(input: { workspaceRoot: string; path: string }) { return this.gitDiff(input); }
  private async validate(set: ChangeSet) { const root = workspace(set?.workspaceRoot); if (!set || typeof set.summary !== "string" || !set.summary.trim() || !Array.isArray(set.files) || !set.files.length || set.files.length > max("CODING_MAX_CHANGED_FILES", 25)) return fail("Invalid change set.", "validation"); let bytes = 0; const seen = new Set<string>(); const baselines: Preview["baselines"] = []; const diffs: Array<{ path: string; operation: string; diff: string; oldSha256: string | null; newSha256: string }> = []; for (const item of set.files) { if (!item || !["create", "update"].includes(item.operation) || typeof item.content !== "string" || item.content.includes("\0")) return fail("Only text create/update is allowed."); const rel = safeRelative(item.path); if (seen.has(rel.toLowerCase())) return fail("Duplicate file path.", "validation"); seen.add(rel.toLowerCase()); bytes += Buffer.byteLength(item.content); if (bytes > max("CODING_MAX_CHANGE_BYTES", 1048576) || Buffer.byteLength(item.content) > max("CODING_MAX_FILE_SIZE_KB", 1024) * 1024) return fail("Change exceeds size limit."); const target = await pathIn(root, rel, item.operation === "create"); let before: { content: string; sha256: string } | null = null; try { before = await textFile(target); } catch (e) { if (!(e instanceof CodingError && e.code === "not_found") && (e as NodeJS.ErrnoException).code !== "ENOENT") throw e; } if (item.operation === "create" && before) return fail("Create target already exists.", "conflict"); if (item.operation === "update" && (!before || !/^[a-f0-9]{64}$/i.test(item.expectedSha256 || "") || before.sha256 !== item.expectedSha256)) return fail("Update hash conflict.", "conflict"); baselines.push({ path: rel, sha256: before?.sha256 || null }); const oldLines = before?.content.split("\n") || []; const newLines = item.content.split("\n"); diffs.push({ path: rel, operation: item.operation, oldSha256: before?.sha256 || null, newSha256: hash(item.content), diff: `--- ${before ? "a/" + rel : "/dev/null"}\n+++ b/${rel}\n@@ -1,${oldLines.length} +1,${newLines.length} @@\n${oldLines.map(s => "-" + s).join("\n")}${oldLines.length ? "\n" : ""}${newLines.map(s => "+" + s).join("\n")}` }); } return { root, baselines, diffs }; }
  async preview(input: ChangeSet) { const checked = await this.validate(input); const id = randomUUID(); this.previews.set(id, { id, set: structuredClone(input), expires: Date.now() + 30 * 60_000, baselines: checked.baselines }); return { previewId: id, summary: input.summary, files: checked.diffs, expiresAt: new Date(Date.now() + 30 * 60_000).toISOString() }; }
  async apply(input: { previewId: string }, audit: { requestId?: number; toolRunId?: number } = {}) { const preview = this.previews.get(input.previewId); if (!preview || preview.expires < Date.now()) return fail("Preview expired or unavailable.", "conflict"); const checked = await this.validate(preview.set); if (JSON.stringify(checked.baselines) !== JSON.stringify(preview.baselines)) return fail("Preview no longer matches source files.", "conflict"); const id = randomUUID(); const folder = join(this.sessionBase, id); const stage = join(folder, "stage"); await mkdir(stage, { recursive: true }); const records: Array<{ path: string; operation: string; beforeSha256: string | null; afterSha256: string }> = []; try { for (let i = 0; i < preview.set.files.length; i++) { const item = preview.set.files[i]; await writeFile(join(stage, String(i)), item.content, { flag: "wx" }); records.push({ path: safeRelative(item.path), operation: item.operation, beforeSha256: checked.baselines[i].sha256, afterSha256: hash(item.content) }); if (item.operation === "update") { const old = await readFile(await pathIn(checked.root, item.path)); await mkdir(join(folder, "before"), { recursive: true }); await writeFile(join(folder, "before", String(i)), old, { flag: "wx" }); } } const rechecked = await this.validate(preview.set); if (JSON.stringify(rechecked.baselines) !== JSON.stringify(checked.baselines)) return fail("Source changed while staging.", "conflict"); const manifest = { id, workspaceRoot: checked.root, timestamp: new Date().toISOString(), status: "prepared", ...audit, files: records }; await writeFile(join(folder, "manifest.json"), JSON.stringify(manifest, null, 2)); const moved: number[] = []; try { for (let i = 0; i < records.length; i++) { const target = await pathIn(checked.root, records[i].path, true); await mkdir(dirname(target), { recursive: true }); await rename(join(stage, String(i)), target); moved.push(i); } manifest.status = "applied"; await writeFile(join(folder, "manifest.json"), JSON.stringify(manifest, null, 2)); await writeFile(join(folder, "after-metadata.json"), JSON.stringify(records, null, 2)); } catch (e) { for (const i of moved.reverse()) { const target = await pathIn(checked.root, records[i].path, true); if (records[i].operation === "create") await rm(target, { force: true }); else await writeFile(target, await readFile(join(folder, "before", String(i)))); } throw e; } this.previews.delete(input.previewId); return { sessionId: id, status: "applied", files: records }; } catch (e) { await rm(folder, { recursive: true, force: true }); throw e; } }
  async sessions() { try { const ids = await readdir(this.sessionBase); const result = []; for (const id of ids.slice(-50).reverse()) { if (!/^[a-f0-9-]{36}$/.test(id)) continue; try { result.push(JSON.parse(await readFile(join(this.sessionBase, id, "manifest.json"), "utf8"))); } catch {} } return result; } catch { return []; } }
  async rollback(input: { sessionId: string }) { if (!/^[a-f0-9-]{36}$/.test(input.sessionId || "")) return fail("Invalid session ID."); const folder = join(this.sessionBase, input.sessionId); let manifest: { workspaceRoot: string; status: string; files: Array<{ path: string; operation: string; afterSha256: string }> }; try { manifest = JSON.parse(await readFile(join(folder, "manifest.json"), "utf8")); } catch { return fail("Session not found.", "not_found"); } const root = workspace(manifest.workspaceRoot); if (manifest.status !== "applied") return fail("Session cannot be rolled back.", "conflict"); for (const item of manifest.files) { const target = await pathIn(root, item.path); if ((await textFile(target)).sha256 !== item.afterSha256) return fail("File changed since apply; rollback blocked.", "conflict"); } for (let i = 0; i < manifest.files.length; i++) { const item = manifest.files[i]; const target = await pathIn(root, item.path); if (item.operation === "create") await rm(target); else { const temp = target + `.freeos-${randomUUID()}.tmp`; await writeFile(temp, await readFile(join(folder, "before", String(i))), { flag: "wx" }); await rename(temp, target); } } manifest.status = "rolled_back"; await writeFile(join(folder, "manifest.json"), JSON.stringify(manifest, null, 2)); return { sessionId: input.sessionId, status: "rolled_back" }; }
  async commandPreview(input: { workspaceRoot: string; command: string; path?: string }) { const root = workspace(input.workspaceRoot); if (input.command === "git status --short") return { workspaceRoot: root, executable: "git", args: ["status", "--short"] }; if (input.command === "git diff") return { workspaceRoot: root, executable: "git", args: ["diff", "--no-ext-diff", "--no-textconv"] }; if (input.command === "git diff -- path" && input.path) { await pathIn(root, input.path); return { workspaceRoot: root, executable: "git", args: ["diff", "--no-ext-diff", "--no-textconv", "--", safeRelative(input.path)] }; } const script = input.command?.startsWith("npm run ") ? input.command.slice(8) : input.command === "npm test" ? "test" : ""; if (!safeScripts.has(script)) return fail("Command is not allowlisted."); let pkg: { scripts?: Record<string, string> }; try { pkg = JSON.parse(await readFile(join(root, "package.json"), "utf8")); } catch { return fail("package.json unavailable."); } if (typeof pkg.scripts?.[script] !== "string") return fail("Script does not exist."); return { workspaceRoot: root, executable: "npm", args: script === "test" ? ["test"] : ["run", script] }; }
  async commandRun(input: { workspaceRoot: string; command: string; path?: string }) { const command = await this.commandPreview(input); if (input.command === "git status --short") return { command, stdout: (await this.gitStatus(input)).status, stderr: "", exitCode: 0 }; if (input.command === "git diff" || input.command === "git diff -- path") return { command, stdout: (await this.gitDiff(input)).diff, stderr: "", exitCode: 0 }; const { stdout, stderr } = await exec(command.executable, command.args, { cwd: command.workspaceRoot, shell: false, windowsHide: true, timeout: max("CODING_COMMAND_TIMEOUT_MS", 120000), maxBuffer: 2 * 1024 * 1024 }); return { command, stdout, stderr, exitCode: 0 }; }
}
export const coding = new CodingWorkspace();
